astro_courses = [
    {
        "code": "FYS2041",
        "name": "Tähtitieteen perusteet I",
        "eng_name": "Basics of Astronomy I",
        "period": [3],
        "year": [1, 2],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": [],
        "themes_theory": 0.25,
        "themes_methods": 0.25,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Coordinate systems, calendars, and time measurement",
            "Telescopes and observations (optical, high-energy, radio, particle)",
            "Radiation quantities (intensity, flux density, luminosity, magnitudes, colours, extinction)",
            "Radiation mechanisms (free-free, synchrotron, and black body; radiative transfer equation)",
            "Celestial mechanics (Kepler’s laws, orbital elements, two-body systems)",
            "Solar system physics (objects, albedos, temperature estimates, exoplanet detection)"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2042",
        "name": "Tähtitieteen perusteet II",
        "eng_name": "Basics of Astronomy II",
        "period": [4],
        "year": [1, 2],
        "content_lectures": 12,
        "content_exercises": 5,
        "content_other": ["5 help sessions for exercises"],
        "themes_theory": 0.25,
        "themes_methods": 0.25,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Lauri Jetsu", "Tuomo Salmi"],
        "topics": [
            "Spectra of stars",
            "Binary stars",
            "Stellar masses",
            "Stellar structure",
            "Stellar evolution",
            "Sun",
            "Variable stars",
            "Compact stars",
            "Star clusters and associations",
            "Interstellar matter",
            "Milky Way",
            "Galaxies",
            "Cosmology",
            "Astrobiology",
            "Exoplanets"
        ],
        "prereqs": ["FYS2041 Tähtieteen perusteet I"]
    },
    {
        "code": "FYS2044",
        "name": "Havaitsevan tähtitieteen peruskurssi I",
        "eng_name": "Observational Astronomy I",
        "period": [1, 2],
        "year": [1, 2],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["6 help session for exercises"],
        "themes_theory": 0.05,
        "themes_methods": 0.10,
        "themes_observations": 0.75,
        "themes_phenomena": 0.10,
        "teachers": ["Lauri Jetsu", "Thomas Hackman"],
        "topics": [
            "History",
            "Atmospheric impact on observations",
            "Optics",
            "Telescopes and Observations",
            "Detectors",
            "CCD-camera",
            "Image processing",
            "Photometry",
            "Polarimetry",
            "Spectroscopy",
            "Astrometry",
            "Modern telescope technology"
        ],
        "prereqs": ["Basics of astronomy I"]
    },
    {
        "code": "FYS2045",
        "name": "Havaitsevan tähtitieteen peruskurssi II",
        "eng_name": "Observational Astronomy II",
        "period": [],
        "year": [],
        "content_lectures": 18,
        "content_exercises": 12,
        "content_other": ["9 lab hours", "practical exercise/report", "exam"],
        "themes_theory": 0.20,
        "themes_methods": 0.30,
        "themes_observations": 0.30,
        "themes_phenomena": 0.20,
        "teachers": [],
        "topics": [
            "Radiative processes",
            "Sources of high-energy emission",
            "High energy Observatories",
            "Galaxy clusters are high energies",
            "XSPEC and basics of spectral analysis",
            "DS9 and basics of surface brightness analysis",
            "Radio telescopes",
            "Antennas and receivers",
            "Spectrometers and single-dish observations",
            "Calibration of radio observations",
            "Radio spectroscopy",
            "Continuum observations",
            "Radio interferometry"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2054",
        "name": "Tähtien rakenne ja kehitys",
        "eng_name": "Stellar Structure and Evolution",
        "period": [3, 4],
        "year": [2, 3],
        "content_lectures": 13,
        "content_exercises": 5,
        "content_other": ["1 computer exercise", "exam"],
        "themes_theory": 0.60,
        "themes_methods": 0.20,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Thomas Hackman", "Joonas Nättilä"],
        "topics": [
            "Stellar structure equations",
            "Diffusion equation",
            "Convection (Ledoux and Schwarzschild criterion)",
            "Rosseland mean opacity",
            "Ideal gas",
            "Radiation pressure",
            "Blackbody radiation",
            "Degenerate electron gas",
            "Saha equation",
            "Nuclear reactions (formation of elements)",
            "Stellar classification",
            "Star formation",
            "Jeans mass",
            "Stellar evolutionary tracks (protostar, pre-main sequence, main sequence, post-main sequence)",
            "Compact stars (white dwarfs, Chandrasekhar mass, neutron stars, Tolman-Oppenheimer-Volkoff limit, black holes)",
            "Planetary nebulae",
            "Supernova"
        ],
        "prereqs": ["Basic astronomy I-II", "Basics of thermophysics"]
    },
    {
        "code": "FYS2046",
        "name": "Astrofysiikan peruskurssi I",
        "eng_name": "Basics of Astrophysics I",
        "period": [3],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.75,
        "themes_methods": 0.10,
        "themes_observations": 0.05,
        "themes_phenomena": 0.10,
        "teachers": ["Joonas Nättilä"],
        "topics": [
            "Brief introduction to the history of astrophysics",
            "Radiative processes, definitions",
            "Black-body radiation",
            "Emission and absorption coefficients",
            "Radiative transfer, solutions to basic radiative transfer problems",
            "Solar limb darkening",
            "Gas physics in the solar atmosphere",
            "Maxwell-Boltzmann distribution",
            "Boltzmann equation for atomic excitation",
            "Saha equation for ionisation",
            "Thermodynamic equilibrium",
            "Stellar atmospheric model calculations"
        ],
        "prereqs": ["Basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "FYS2047",
        "name": "Astrofysiikan peruskurssi II",
        "eng_name": "Basics of Astrophysics II",
        "period": [4],
        "year": [2, 3],
        "content_lectures": 12,
        "content_exercises": 6,
        "content_other": ["exam"],
        "themes_theory": 0.50,
        "themes_methods": 0.20,
        "themes_observations": 0.10,
        "themes_phenomena": 0.20,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Extinction, absorption by classic dipole",
            "Scattering by classic dipole",
            "Continuum absorption (dipole, Hydrogen, other elements)",
            "Hydrogen ionisation and recombinations",
            "Transition probabilities",
            "Spectral line emission and absorption; spectral line profiles",
            "Radiative transfer equation",
            "Neutral hydrogen in interstellar space",
            "Continuum emission and absorption in interstellar space"
        ],
        "prereqs": ["FYS2046 Astrofysiikan peruskurssi I", "basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "FYS2043",
        "name": "Johdatus avaruusplasmafysiikkaan",
        "eng_name": "Introduction to Space Plasma Physics",
        "period": [1],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 5,
        "content_other": [],
        "themes_theory": 0.30,
        "themes_methods": 0.10,
        "themes_observations": 0.20,
        "themes_phenomena": 0.40,
        "teachers": ["Emilia Kilpua", "Thomas Hackman", "Taina Kurki-Suonio", "Sanni Hoilijoki", "Kai Nordlund"],
        "topics": [
            "Basics of plasma physics phenomena and theory",
            "Basic phenomena of space plasma physics",
            "Astrophysical plasma phenomena",
            "Fusion in stars",
            "Origin of elements",
            "Magnetic activity of stars",
            "Fusion on Earth",
            "Plasma and materials"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2027",
        "name": "Mekaniikka",
        "eng_name": "Mechanics",
        "period": [1],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["7 problem set help sessions", "6 case studies"],
        "themes_theory": 0.75,
        "themes_methods": 0.25,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Mikael Granvik", "Elina Keihänen"],
        "topics": [
            "Dimensional analysis",
            "2-body problem",
            "Newton’s law of universal gravitation",
            "Derivation of Kepler’s laws",
            "Kepler equation",
            "Lagrangian formalism",
            "Variational calculus",
            "Principle of least action",
            "Lagrangian equations of motion",
            "Symmetries in Lagrangian formalism",
            "Coupled oscillators",
            "Dynamics of rigid bodies",
            "Transitions between rotating and inertial frames",
            "Hamiltonian mechanics",
            "Hamilton’s equations of motion",
            "Canonical transformations"
        ],
        "prereqs": ["Basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills", "basic skills in numerics", "beneficial: FYMM IIb"]
    },
    {
        "code": "FYS2055",
        "name": "Taivaanmekaniikka",
        "eng_name": "Celestial Mechanics",
        "period": [2],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["7 problem set help sessions", "6 case studies"],
        "themes_theory": 0.40,
        "themes_methods": 0.40,
        "themes_observations": 0.0,
        "themes_phenomena": 0.20,
        "teachers": ["Mikael Granvik"],
        "topics": [
            "Applications of the 2-body problem",
            "Perturbation theory",
            "N-body problem",
            "Numerical integrators",
            "3-body problem theory",
            "Applications of 3-body problem",
            "Disturbing function",
            "Orbit computation"
        ],
        "prereqs": ["FYS2027 Mekaniikka", "basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills", "basic skills in scientific programming", "beneficial: FYMM IIa"]
    },
    {
        "code": "FYS2051",
        "name": "Aurinkokunnan fysiikka",
        "eng_name": "Solar System Physics",
        "period": [3, 4],
        "year": [2, 3],
        "content_lectures": 12,
        "content_exercises": 5,
        "content_other": ["presentation", "3 essays (1/3 mandatory)", "programming project", "home exam"],
        "themes_theory": 0.50,
        "themes_methods": 0.10,
        "themes_observations": 0.20,
        "themes_phenomena": 0.20,
        "teachers": ["Anne Virkki"],
        "topics": [
            "Solar System objects",
            "Solar System formation theories",
            "Planetary geophysical processes (heat, radiation, petrophysics, atmospheres, oceans)",
            "(Planetary) radiation quantities (intensity, flux density, luminosity, magnitudes)",
            "Reflectivity, albedos, and integrated brightness of planetary bodies",
            "Observation methods (photometry, spectroscopy, polarimetry and their combinations)",
            "Empirical and analytical scattering laws",
            "HG / HG1G2 / HG12 systems",
            "Multiwavelength observations of Solar System objects from UV to radio",
            "Fundamental light scattering concepts (Stokes, scattering matrix, scattering quantities)",
            "Exoplanet observations",
            "Requirements of (extraterrestrial) life",
            "Spacecraft missions for planetary exploration",
            "Presenting scientific information in written and oral forms, reference critique",
            "Numerical implementation of integrated brightness for discretised spheroids"
        ],
        "prereqs": ["Basics of astronomy (TäPe) I-II", "Numerical methods (TiLa) I", "MApu I-III"]
    },
    {
        "code": "FYS2052",
        "name": "Galaksit ja kosmologia",
        "eng_name": "Galaxies and Cosmology",
        "period": [1, 2],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.70,
        "themes_methods": 0.15,
        "themes_observations": 0.05,
        "themes_phenomena": 0.10,
        "teachers": ["Peter Johansson"],
        "topics": [
            "Introduction to galaxies. Galaxy classification, stellar populations and the interstellar medium.",
            "Galactic dynamics: Poisson equation, virial theorem, relaxation timescales, Boltzmann equation and phase-space.",
            "Cosmology: FRW-metric, angular-diameter and luminosity distances, Friedmann equations and their solutions",
            "The age of the Universe. Dark matter and dark energy. Elliptical galaxies.",
            "Spiral galaxies and lenticular galaxies.",
            "Active galaxies and supermassive black holes. The Local Group of galaxies.",
            "Galaxy clusters and the large-scale structure of the Universe. The early Universe, inflation theory and the formation of structure.",
            "Galaxy formation and evolution, a theoretical framework."
        ],
        "prereqs": ["Basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "FYS2053",
        "name": "Linnunradan rakenne",
        "eng_name": "Structure of the Milky Way",
        "period": [1, 2],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.45,
        "themes_methods": 0.10,
        "themes_observations": 0.40,
        "themes_phenomena": 0.05,
        "teachers": ["Peter Johansson", "Jorma Harju"],
        "topics": [
            "Introduction to the Milky Way",
            "Observing the distances and velocities of stars in the Milky Way",
            "Interstellar dust and extinction",
            "Stellar statistics",
            "Structure of the Milky Way: Stellar and gaseous disc, stellar bulge, stellar halo, central supermassive black hole, dark matter halo",
            "GAIA satellite: Revolutionising the study of the Milky Way. Stellar kinematics in the Milky Way",
            "Galactic rotation. The Oort constants. The Solar orbit and the orbits of other stars in the Milky Way",
            "The Milky Way rotation curve and spiral structure. The mass density in the vicinity of the Sun",
            "Formation and evolution of the Milky Way"
        ],
        "prereqs": ["Basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "BSPH2009",
        "name": "Basics of Astronomy I",
        "eng_name": "Basics of Astronomy I",
        "period": [],
        "year": [],
        "content_lectures": 26,
        "content_exercises": 6,
        "content_other": ["exam"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Finoguenov + everyone"],
        "topics": [
            "Spherical Astronomy",
            "Observational methods I, II",
            "Facilities",
            "Radiative processes I, II",
            "Stellar spectra, structure, evolution",
            "ISM and SF",
            "Variable and binary stars",
            "Compact objects",
            "SN nucleosynthesis and chemical enrichment models"
        ],
        "prereqs": []
    },
    {
        "code": "PAP302",
        "name": "Open Problems in Modern Astrophysics",
        "eng_name": "Open Problems in Modern Astrophysics",
        "period": [1, 2],
        "year": [4],
        "content_lectures": 14,
        "content_exercises": 7,
        "content_other": ["7 problem set discussion sessions", "exam"],
        "themes_theory": 0.15,
        "themes_methods": 0.05,
        "themes_observations": 0.15,
        "themes_phenomena": 0.65,
        "teachers": ["Peter Johansson", "Till Sawala"],
        "topics": [
            "The detection and properties of Extrasolar planets",
            "Gamma-ray Bursts: Observation and Theory",
            "Stellar dynamics near massive black holes and gravitational waves",
            "The formation and evolution of star clusters",
            "Nearby dwarf galaxies: testing the limits of structure formation",
            "Massive galaxies at high redshifts – a challenge for structure formation?",
            "Dark Energy and the Hubble tension"
        ],
        "prereqs": ["Bachelor studies in astronomy or equivalent"]
    },
    {
        "code": "PAP303",
        "name": "Statistical Inverse Methods",
        "eng_name": "Statistical Inverse Methods",
        "period": [3, 4],
        "year": [4],
        "content_lectures": 12,
        "content_exercises": 12,
        "content_other": ["home exam"],
        "themes_theory": 0.0,
        "themes_methods": 1.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Antti Penttilä"],
        "topics": [
            "Distributions",
            "Statistical inference",
            "Statistical tests",
            "Linear model",
            "Non-linear model",
            "Non-parametric methods",
            "Multivariate methods",
            "Bayesian inference",
            "Monte Carlo methods",
            "Markov chain Monte Carlo",
            "Artificial neural networks"
        ],
        "prereqs": ["Numerical methods (TiLa) I", "MApu I-III"]
    },
    {
        "code": "PAP304",
        "name": "Plasma Physics",
        "eng_name": "Plasma Physics",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 13,
        "content_exercises": 6,
        "content_other": [],
        "themes_theory": 0.70,
        "themes_methods": 0.0,
        "themes_observations": 0.10,
        "themes_phenomena": 0.20,
        "teachers": ["Minna Palmroth"],
        "topics": [
            "Basic plasma parameters",
            "Single particle motion",
            "Kinetic plasma description",
            "Macroscopic plasma description",
            "MHD waves",
            "Cold plasma waves"
        ],
        "prereqs": []
    },
    {
        "code": "PAP323",
        "name": "Advanced Space Plasma Physics",
        "eng_name": "Advanced Space Plasma Physics",
        "period": [3, 4],
        "year": [5],
        "content_lectures": 24,
        "content_exercises": 12,
        "content_other": [],
        "themes_theory": 0.70,
        "themes_methods": 0.10,
        "themes_observations": 0.0,
        "themes_phenomena": 0.20,
        "teachers": ["Urs Ganse"],
        "topics": [
            "Detailed particle motion in EM fields, current sheets",
            "Galactic Cosmic Rays and Solar Energetic Particles",
            "Wave propagation in dielectric and stratified media",
            "Vlasov theory and Landau damping",
            "MHD (force-free fields and flux ropes)",
            "Plasma instabilities",
            "Collisionless shock waves",
            "Magnetic reconnection",
            "Solar dynamo",
            "Radiation and scattering",
            "Transport (Fokker-Planck theory)"
        ],
        "prereqs": []
    },
    {
        "code": "PAP324",
        "name": "Numerical Space Physics",
        "eng_name": "Numerical Space Physics",
        "period": [4],
        "year": [5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["practical hands-on exercises"],
        "themes_theory": 0.50,
        "themes_methods": 0.10,
        "themes_observations": 0.0,
        "themes_phenomena": 0.40,
        "teachers": ["Jens Pomoell", "Daniel Price"],
        "topics": [
            "Simulation methods in space physics",
            "Running simulations and analysing the output",
            "Principles of numerical methods (focus on MHD)"
        ],
        "prereqs": []
    },
    {
        "code": "PAP321",
        "name": "Solar Physics",
        "eng_name": "Solar Physics",
        "period": [3],
        "year": [5],
        "content_lectures": 12,
        "content_exercises": 3,
        "content_other": ["student seminar"],
        "themes_theory": 0.40,
        "themes_methods": 0.20,
        "themes_observations": 0.0,
        "themes_phenomena": 0.40,
        "teachers": ["Ranadeep Sarkar", "Eleanna Asvestari", "Simon Good"],
        "topics": [
            "Formation and evolution of the Sun and Solar System",
            "Standard solar model",
            "Solar atmosphere",
            "Solar oscillations and helioseismology",
            "Convection and solar rotation",
            "Solar dynamo and solar cycle",
            "Solar wind",
            "Solar eruptions"
        ],
        "prereqs": []
    },
    {
        "code": "PAP305",
        "name": "Space Applications of Plasma Physics",
        "eng_name": "Space Applications of Plasma Physics",
        "period": [2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["practical hands-on exercises"],
        "themes_theory": 0.20,
        "themes_methods": 0.70,
        "themes_observations": 0.0,
        "themes_phenomena": 0.10,
        "teachers": ["Eleanna Asvestari", "Lucile Turc"],
        "topics": [
            "Basics of the Sun, its atmosphere",
            "Solar wind and interplanetary shocks",
            "Earth’s magnetosphere and ionosphere",
            "Magnetospheric storms and substorms",
            "Space weather",
            "Key data sets in space physics"
        ],
        "prereqs": []
    },
    {
        "code": "PAP354",
        "name": "Space and Astrophysical Plasma Turbulence",
        "eng_name": "Space and Astrophysical Plasma Turbulence",
        "period": [2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 3,
        "content_other": ["2 computer exercises", "seminar", "exam"],
        "themes_theory": 0.70,
        "themes_methods": 0.10,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Simon Good", "Joonas Nättilä"],
        "topics": [
            "MHD equations",
            "Hydrodynamical (Kolmogorov) turbulence",
            "Weak wave turbulence",
            "Strong MHD Turbulence",
            "Intermittency",
            "Fermi-II particle acceleration mechanism"
        ],
        "prereqs": []
    },
    {
        "code": "PAP306",
        "name": "Advanced Course in Observational Astronomy I",
        "eng_name": "Advanced Course in Observational Astronomy I",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["20 hours observing during intense week", "individual report"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov"],
        "topics": [
            "Principles of optical imaging and spectroscopy",
            "Telescopes: mounts, hardware and operations",
            "Nordic Optical Telescope and NOT fellows",
            "NOT Telescope Control System and its commands",
            "ALFOSC/NOT operation manual",
            "Preparation for the observations and observing tools",
            "Project introduction and target preparation, finding chats and upload",
            "Project science and its requirements on observations and data reduction",
            "Observing guide and tips",
            "Remote observing tools and preparation of NOT Observational Blocks",
            "NOTCam and its commands",
            "Preparation for observations at Turku"
        ],
        "prereqs": []
    },
    {
        "code": "PAP307",
        "name": "Advanced Course in Observational Astronomy II",
        "eng_name": "Advanced Course in Observational Astronomy II",
        "period": [4],
        "year": [4, 5],
        "content_lectures": 24,
        "content_exercises": 0,
        "content_other": ["intense week in Turku", "4 assignments"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov"],
        "topics": [
            "ESO instrumentation on Paranal and future developments on Armazones",
            "ALMA: telescopes, operations, data reduction",
            "4MOST/VISTA facility and observing tools",
            "VLT data analysis using selected instruments: KMOS, MUSE, UVES, XSHOOTER, SoX",
            "ESO proposal writing",
            "VST and data analysis",
            "JWST and data analysis",
            "Euclid and its data repository",
            "Data visualization tools",
            "ESO data archive"
        ],
        "prereqs": []
    },
    {
        "code": "PAP308",
        "name": "Special Course in Observational Astronomy",
        "eng_name": "Special Course in Observational Astronomy",
        "period": [],
        "year": [4, 5],
        "content_lectures": 24,
        "content_exercises": 0,
        "content_other": ["24 hours of practical work", "presentation"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov", "Clif Kirkpatrick"],
        "topics": [
            "IRAF installation",
            "Optical imaging reduction",
            "Bias and bias subtraction",
            "Sensitivity and using sky/dome flats",
            "Optical spectral reduction",
            "Basic processing steps",
            "Tracing the spectrum",
            "Identification of the spectral features and redshift measurement",
            "NIR image reduction and spectroscopy",
            "Software servers at Turku and remote data analysis",
            "Preparation for observations",
            "Calibrations during the night and data retrieval",
            "NOT data processing"
        ],
        "prereqs": []
    },
    {
        "code": "PAP309",
        "name": "Interstellar Matter",
        "eng_name": "Interstellar Matter",
        "period": [2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 4,
        "content_other": ["report work", "exam"],
        "themes_theory": 0.30,
        "themes_methods": 0.20,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Observations of the interstellar medium",
            "Stability and structure of interstellar clouds",
            "Collapse of cloud cores and protostellar evolution",
            "High-mass star formation",
            "Astrochemistry"
        ],
        "prereqs": []
    },
    {
        "code": "PAP311",
        "name": "Small Bodies in the Solar System",
        "eng_name": "Small Bodies in the Solar System",
        "period": [1, 2],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["13 help sessions", "13 learning logs", "13 self-assessments", "exam"],
        "themes_theory": 0.20,
        "themes_methods": 0.10,
        "themes_observations": 0.30,
        "themes_phenomena": 0.40,
        "teachers": ["Mikael Granvik", "Eric MacLennan"],
        "topics": [
            "Asteroid surveys and populations",
            "Asteroid astrometry and orbits",
            "Asteroid photometry and rotations",
            "Asteroid shapes",
            "Asteroid spectroscopy and surface composition",
            "Yarkovsky and YORP effects",
            "Thermal-infrared observations and thermophysical modeling",
            "Asteroid systems",
            "Asteroid families",
            "Active asteroids and meteors",
            "Asteroid formation, and dynamical and collisional evolution",
            "Transneptunian objects and Oort-cloud objects",
            "Centaurs and comets"
        ],
        "prereqs": ["Bachelor courses in astronomy with emphasis on FYS2027, FYS2055, FYS2051"]
    },
    {
        "code": "PAP312",
        "name": "Time Series Analysis in Astronomy",
        "eng_name": "Time Series Analysis in Astronomy",
        "period": [1],
        "year": [5],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["Assignment(-s) each week"],
        "themes_theory": 0.05,
        "themes_methods": 0.85,
        "themes_observations": 0.05,
        "themes_phenomena": 0.05,
        "teachers": ["Lauri Jetsu"],
        "topics": [
            "Python coding",
            "Discrete Chi-square Method (DCM)",
            "Discrete Fourier Transform (DFT)",
            "DCM: Theory, programming, application",
            "DCM and DFT application to simulated data",
            "DCM and DFT performance comparison",
            "Time Series Analysis, Simulation of astrophysical data, Linear and non-linear models",
            "Multiperiodicity, DFT pre-whitening, De-trending, Bootstrap, Fisher-test, Nested models"
        ],
        "prereqs": ["Tila I or equivalent Python programming skills"]
    },
    {
        "code": "PAP313",
        "name": "Variable Stars",
        "eng_name": "Variable Stars",
        "period": [1, 2],
        "year": [5],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["Assignment(-s) each week"],
        "themes_theory": 0.05,
        "themes_methods": 0.70,
        "themes_observations": 0.15,
        "themes_phenomena": 0.10,
        "teachers": ["Lauri Jetsu"],
        "topics": [
            "Discrete Chi-square Method (DCM)",
            "Discrete Fourier Transform (DFT)",
            "DCM and DFT applications to real variable star data",
            "DCM: theory, programming and application",
            "DCM and DFT performance comparison",
            "DCM predictive multiperiodic models: theory and application",
            "Python coding",
            "Chromospherically active stars: Differential rotation, active longitudes, activity cycles",
            "Binary star O-C data: Light time effect, Applegate effect, Apsidal motion, Mass transfer"
        ],
        "prereqs": ["Tila I or equivalent Python programming skills"]
    },
    {
        "code": "PAP351",
        "name": "Stellar magnetic activity",
        "eng_name": "Stellar magnetic activity",
        "period": [3, 4],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["exam"],
        "themes_theory": 0.30,
        "themes_methods": 0.20,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Thomas Hackman"],
        "topics": [
            "Basic MHD concepts",
            "Solar and stellar dynamos",
            "Numerical dynamo simulations",
            "Manifestations of solar and stellar magnetic activity",
            "Solar/stellar corona and winds",
            "Star-planet magnetic interaction",
            "Observing solar and stellar magnetic activity",
            "Inversion methods (Doppler imaging, photometric inversion)"
        ],
        "prereqs": ["Bachelor courses of astronomy", "Basic physics courses", "MApu I-III", "Numerical methods (TiLa I)", "Plasma physics (recommended)", "Statistical inverse methods (rec.)", "Space and Astrophysical Plasma Turbulence (useful)"]
    },
    {
        "code": "PAP314",
        "name": "Introduction to light scattering",
        "eng_name": "Introduction to light scattering",
        "period": [4],
        "year": [3, 4],
        "content_lectures": 14,
        "content_exercises": 5,
        "content_other": ["project task", "home exam"],
        "themes_theory": 0.60,
        "themes_methods": 0.20,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Karri Muinonen", "Antti Penttilä", "Anne Virkki", "Yehor Surkov", "Zuri Gray"],
        "topics": [
            "Introduction to scattering",
            "Scattering at a planar interface",
            "Mie scattering",
            "Ray optics",
            "Angular scattering",
            "Rayleigh scattering",
            "Effective medium approximations",
            "Rayleigh-Gans scattering",
            "Transition matrix method (T-matrix method)",
            "Radar scattering",
            "Applications"
        ],
        "prereqs": ["Electrodynamics", "Numerical methods (TiLa) I", "MApu I-III"]
    },
    {
        "code": "PAP315",
        "name": "Computational light scattering",
        "eng_name": "Computational light scattering",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 5,
        "content_other": ["2 project tasks", "home exam"],
        "themes_theory": 0.40,
        "themes_methods": 0.40,
        "themes_observations": 0.0,
        "themes_phenomena": 0.20,
        "teachers": ["Karri Muinonen", "Antti Penttilä", "Anne Virkki", "Yehor Surkov", "Zuri Gray"],
        "topics": [
            "Introduction to single scattering",
            "Scattering by a spherical particle (Mie scattering)",
            "Discrete-dipole approximation, volume-integral equation",
            "Discrete-dipole approximation, particle near a surface",
            "T-matrix method",
            "Ray optics approximation",
            "Introduction to multiple scattering (radiative transfer and coherent backscattering)",
            "Monte Carlo methods for multiple scattering",
            "Superposition T-matrix method",
            "Rough-surface scattering modeling",
            "Radar scattering",
            "Geometric optics for close-packed media"
        ],
        "prereqs": ["Electrodynamics", "Numerical methods (TiLa) I", "MApu I-III"]
    },
    {
        "code": "PAP316",
        "name": "Astrophysical light scattering problems",
        "eng_name": "Astrophysical light scattering problems",
        "period": [4],
        "year": [3, 4],
        "content_lectures": 14,
        "content_exercises": 3,
        "content_other": ["2 inverse methods project tasks", "home exam"],
        "themes_theory": 0.25,
        "themes_methods": 0.20,
        "themes_observations": 0.25,
        "themes_phenomena": 0.10,
        "teachers": ["Karri Muinonen", "Antti Penttilä", "Anne Virkki", "Yehor Surkov", "Zuri Gray"],
        "topics": [
            "Introduction to photometry, polarimetry, and spectrometry",
            "Experimental scattering measurements",
            "Polarimetry, photometry, and spectrometry of the Moon",
            "Mercury, Venus, Mars",
            "Asteroids",
            "Interplanetary dust",
            "Comets",
            "Icy moons of outer planets, Saturn’s rings",
            "Transneptunian objects",
            "Interstellar dust",
            "Exoplanets"
        ],
        "prereqs": ["Electrodynamics", "Numerical methods (TiLa) I", "MApu I-III"]
    },
    {
        "code": "PAP317",
        "name": "Galactic dynamics",
        "eng_name": "Galactic dynamics",
        "period": [3, 4],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.75,
        "themes_methods": 0.15,
        "themes_observations": 0.05,
        "themes_phenomena": 0.05,
        "teachers": ["Peter Johansson"],
        "topics": [
            "Introduction to galactic dynamics",
            "Potential theory",
            "The Milky Way potential and Poisson solvers",
            "Orbits in static spherical potentials",
            "Orbits in axisymmetric and non-axisymmetric potentials",
            "Numerical orbit integration",
            "The collisionless Boltzmann equation",
            "Distribution functions for spherical isotropic and anisotropic systems",
            "Jeans and virial equations",
            "Stellar kinematics as a mass detector: Black holes and dark matter",
            "Choice of equilibrium and chaotic dynamics",
            "Stability of collisionless systems",
            "Disk dynamics and spiral structure",
            "Kinetic theory and relaxation processes",
            "Mergers of galaxies and galaxy formation"
        ],
        "prereqs": ["Bachelor studies in astronomy or equivalent", "Galaxies and cosmology", "Mechanics and Celestial mechanics"]
    },
    {
        "code": "PAP318",
        "name": "Galaxy formation and evolution",
        "eng_name": "Galaxy formation and evolution",
        "period": [1, 2],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.70,
        "themes_methods": 0.10,
        "themes_observations": 0.15,
        "themes_phenomena": 0.05,
        "teachers": ["Peter Johansson"],
        "topics": [
            "Introduction to galaxy formation and overview",
            "Observations of galaxies",
            "Cosmology overview",
            "Linear evolution of small density perturbations",
            "Jeans instabilities and horizons in an expanding Universe",
            "Baryonic and dark matter models of galaxy formation",
            "Correlation functions and the spectrum of the initial fluctuations",
            "Non-linear evolution of dark matter haloes",
            "Formation and evolution of gaseous haloes",
            "Star formation and stellar feedback in galaxies",
            "Formation of disk galaxies",
            "Galaxy interactions and transformations",
            "Formation of elliptical galaxies",
            "Formation of active galaxies and the physics of supermassive black holes"
        ],
        "prereqs": ["Bachelor studies in astronomy or equivalent", "Galaxies and cosmology", "Milky Way structure", "Basic courses in astrophysics"]
    },
    {
        "code": "PAP319",
        "name": "High Energy Astrophysics",
        "eng_name": "High Energy Astrophysics",
        "period": [],
        "year": [],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["24 hours of lab work", "grade based on labs"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov"],
        "topics": [
            "Radiative processes",
            "Sources of high-energy emission and their models",
            "Particle acceleration",
            "High energy Observatories",
            "Galaxy clusters are high energies",
            "Hydrostatic Equilibrium and mass estimates",
            "XMM-Newton data reduction",
            "High energy emission from accreting black holes",
            "Statical tools for the analysis of high-energy spectra",
            "High energy data repositories and software",
            "Spectral simulations, and mission forecasts, proposal tools",
            "Quantum electrodynamic processes at high energies",
            "X-IFU/Athena forecasts"
        ],
        "prereqs": []
    },
    {
        "code": "PAP320",
        "name": "Radiative Transfer",
        "eng_name": "Radiative Transfer",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 4,
        "content_other": ["report work", "exam"],
        "themes_theory": 0.30,
        "themes_methods": 0.50,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Radiative transfer equation",
            "Setup of radiative transfer models",
            "Basic radiative transfer methods (ray tracing and Monte Carlo)",
            "Continuum radiative transfer",
            "Dust physics and temperature calculation, stochastic heating",
            "Improvements of the Monte Carlo method",
            "Line radiative transfer",
            "Approximate solutions",
            "Exact solutions with ray tracing and Monte Carlo",
            "Radiative transfer in multiphysics models",
            "Model discretisations (spatial, angular, and frequency grids)",
            "Parallel radiative transfer"
        ],
        "prereqs": []
    }
]


additional_courses = [
    {
        "code": "MATR322",
        "name": "Numerical Methods in Scientific Computing",
        "eng_name": "Numerical Methods in Scientific Computing",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": []
    },
    {
        "code": "FYS1010",
        "name": "Matemaattiset apuneuvot I",
        "eng_name": "Mathematical Methods I",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Vector calculus",
            "Power series",
            "Differential calculus",
            "Integral calculus"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1011",
        "name": "Matemaattiset apuneuvot II",
        "eng_name": "Mathematical Methods II",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Basics of complex numbers and functions",
            "Basics of ordinary differential equations (integrating factor, trial function, separability)",
            "Basics of linear algebra"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1012",
        "name": "Matemaattiset apuneuvot III",
        "eng_name": "Mathematical Methods III",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Differential calculus of vector functions: space curves, gradient, divergence, curl",
            "Integral calculus of vector functions: line, surface and volume integrals",
            "Gauss's and Stokes's theorems"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2010",
        "name": "Fysiikan matemaattiset menetelmät Ia",
        "eng_name": "Mathematical Methods for Physicists Ia",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Complex numbers in depth and their functions",
            "Line integral of a complex function",
            "Series expansions of complex functions (Taylor and Laurent series)",
            "Residue calculus"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2011",
        "name": "Fysiikan matemaattiset menetelmät Ib",
        "eng_name": "Mathematical Methods for Physicists Ib",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Analytic continuation",
            "Special functions (Gamma, beta functions)",
            "Series expansions (asymptotic series and Fourier series)",
            "Fourier and Laplace transforms",
            "Dirac delta"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2012",
        "name": "Fysiikan matemaattiset menetelmät IIa",
        "eng_name": "Mathematical Methods for Physicists IIa",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Partial differential equations (PDE)",
            "Second order ordinary differential equations (ODE)",
            "Special functions"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2013",
        "name": "Fysiikan matemaattiset menetelmät IIb",
        "eng_name": "Mathematical Methods for Physicists IIb",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Calculus of variations",
            "Functional derivative",
            "Sturm-Liouville equation",
            "Hilbert space",
            "Operators",
            "Spectral theory (if time permits)",
            "Probability calculus (very little)"
        ],
        "prereqs": []
    },
    {
        "code": "TCM304",
        "name": "Fysiikan matemaattiset menetelmät IIIa",
        "eng_name": "Mathematical Methods for Physicists IIIa",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["N/A"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Group theory",
            "Representation theory",
            "Topology"
        ],
        "prereqs": []
    },
    {
        "code": "TCM305",
        "name": "Fysiikan matemaattiset menetelmät IIIb",
        "eng_name": "Mathematical Methods for Physicists IIIb",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["N/A"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Differentiable manifolds",
            "Riemannian geometry: Geodesics, Killing vectors",
            "Semi-simple Lie algebras and their unitary representations"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1013",
        "name": "Tieteellinen laskenta I",
        "eng_name": "Scientific Computing I",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Programming basics with Python",
            "Structures: for, if, while",
            "Basics of Python language",
            "Jupyter Notebook basics",
            "Linux OS basic commands",
            "Basic concepts of statistical methods (e.g. least squares fit)",
            "Basics of using databases for scientific search",
            "Basics of creating a scientific document (LaTeX/Writing)"
        ],
        "prereqs": []
    },
    {
        "code": "N/A",
        "name": "Tieteellinen laskenta II",
        "eng_name": "Scientific Computing II",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Fortran programming language"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1014",
        "name": "Havaintojen tilastollinen käsittely",
        "eng_name": "Statistical Analysis of Observations",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Basics of statistical processing",
            "Statistical parameters",
            "Basics of probability math and distributions (normal, binomial, poisson)",
            "Statistical estimation and testing (t-test, chi^2, etc.)",
            "Basics of correlation and regression analysis",
            "Basics of time series analysis",
            "Basics of chaos theory"
        ],
        "prereqs": []
    },
    {
        "code": "MOOC1",
        "name": "Ohjelmoinnin perusteet (MOOC)",
        "eng_name": "Basics of Programming (MOOC)",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Python"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Python",
            "Similar to TiLA1 but more thorough"
        ],
        "prereqs": []
    },
    {
        "code": "MOOC2",
        "name": "Ohjelmoinnin jatkokurssi (MOOC)",
        "eng_name": "Advanced Programming (MOOC)",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Advanced Python"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Advanced Python",
            "Object-oriented programming",
            "Classes"
        ],
        "prereqs": []
    },
    {
        "code": "N/A",
        "name": "Introduction to Machine Learning",
        "eng_name": "Introduction to Machine Learning",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": []
    },
    {
        "code": "N/A",
        "name": "Advanced Machine Learning",
        "eng_name": "Advanced Machine Learning",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": []
    },
    {
        "code": "FYS1001",
        "name": "Vuorovaikutukset ja kappaleet",
        "eng_name": "Interactions and Bodies",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op; Matter & Interactions ch 1-8"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Conservation of momentum",
            "Conservation of energy",
            "Forces",
            "4 fundamental interactions",
            "Internal energy",
            "Quantization of energy"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1002",
        "name": "Vuorovaikutukset ja aine",
        "eng_name": "Interactions and Matter",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op; Matter & Interactions ch 9-12 + gas supplement"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Translational, rotational and vibrational energy",
            "Collisions",
            "Angular momentum",
            "Entropy",
            "Gases and heat engines"
        ],
        "prereqs": []
    },
    {
        "code": "FYS2027",
        "name": "Mekaniikka",
        "eng_name": "Mechanics",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Lagrange mechanics",
            "Hamilton mechanics",
            "Rotation (Euler angles)",
            "Two-body interaction"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1003",
        "name": "Sähkömagnetismi",
        "eng_name": "Electromagnetism",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op; Matter & Interactions ch 13-20"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Electric field, force, potential, polarization, charge distributions",
            "Magnetic field, force",
            "Circuits"
        ],
        "prereqs": []
    },
    {
        "code": "FYS1004",
        "name": "Säteilykentät ja fotonit",
        "eng_name": "Radiation Fields and Photons",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["5 op; Matter & Interactions ch 21-23"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Maxwell's equations",
            "Electromagnetic radiation"
        ],
        "prereqs": []
    },
    {
        "code": "ElectroI",
        "name": "Electrodynamics I",
        "eng_name": "Electrodynamics I",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Based on Griffiths (start)"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Electrostatics: Electric fields, divergence, curl, potential, work and energy, conductors",
            "Potentials: Laplace equation, method of images, multipole expansion",
            "Electric fields in matter: Polarization, electric displacement, linear dielectrics",
            "Magnetostatics: Lorentz force, Biot-Savart law, Ampère’s law, magnetic vector potential",
            "Magnetic fields in matter: Magnetization, auxiliary field H, linear and non-linear media",
            "Electrodynamics: Electromotive force, induction, Maxwell’s equations"
        ],
        "prereqs": ["Teoreettisen fysiikan taidot"]
    },
    {
        "code": "ElectroII",
        "name": "Electrodynamics II",
        "eng_name": "Electrodynamics II",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Based on Griffiths (end)"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Conservation laws: continuity equation, Poynting’s theorem, Maxwell’s stress tensor",
            "Electromagnetic waves: EM waves in vacuum, EM waves in matter, dispersion and absorption, guided waves",
            "Potentials and fields: potential formulation, retarded potentials, Jefimenko, Liénard-Wiechert, moving charges",
            "Radiation: Electric and magnetic dipole radiation, arbitrary sources, radiation reaction",
            "Electrodynamics and relativity: Special relativity, field tensor, Lorentz transformation"
        ],
        "prereqs": []
    },
    {
        "code": "N/A",
        "name": "Termofysiikan perusteet",
        "eng_name": "Basics of Thermophysics",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": []
    },
    {
        "code": "N/A",
        "name": "Termodynaamiset potentiaalit",
        "eng_name": "Thermodynamic Potentials",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": []
    }
]
