astro_courses = [
    {
        "code": "FYS2041",
        "name": "Tähtitieteen perusteet I",
        "eng_name": "Basics of Astronomy I",
        "op": 5,
        "description": "The course gives an overview of the study and research of astrophysics and space physics, as well as the most important concepts in the field.",
        "period": [3],
        "year": [1, 2],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": [],
        "themes_theory": 0.25,
        "themes_methods": 0.25,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Coordinate systems, calendars, and time measurement",
            "Telescopes and observations (optical, high-energy, radio, particle)",
            "Radiation quantities (intensity, flux density, luminosity, magnitudes, colours, extinction)",
            "Radiation mechanisms (free-free, synchrotron, and black body; radiative transfer equation)",
            "Celestial mechanics (Kepler’s laws, orbital elements, two-body systems)",
            "Solar system physics (objects, albedos, temperature estimates, exoplanet detection)"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2042",
        "name": "Tähtitieteen perusteet II",
        "eng_name": "Basics of Astronomy II",
        "op": 5,
        "description": "The course deepens the understanding of astronomical phenomena, such as stellar structure, the Milky Way, and cosmology.",
        "period": [4],
        "year": [1, 2],
        "content_lectures": 12,
        "content_exercises": 5,
        "content_other": ["5 help sessions for exercises"],
        "themes_theory": 0.25,
        "themes_methods": 0.25,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Lauri Jetsu", "Tuomo Salmi"],
        "topics": [
            "Spectra of stars",
            "Binary stars",
            "Stellar masses",
            "Stellar structure",
            "Stellar evolution",
            "Sun",
            "Variable stars",
            "Compact stars",
            "Star clusters and associations",
            "Interstellar matter",
            "Milky Way",
            "Galaxies",
            "Cosmology",
            "Astrobiology",
            "Exoplanets"
        ],
        "prereqs": ["Tähtitieteen perusteet I"],
        "prereqs_other": []
    },
    {
        "code": "FYS2044",
        "name": "Havaitsevan tähtitieteen peruskurssi I",
        "eng_name": "Observational Astronomy I",
        "op": 5,
        "description": "The course introduces optical observation instruments, observational methods, and data processing.",
        "period": [1, 2],
        "year": [1, 2],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["6 help session for exercises"],
        "themes_theory": 0.05,
        "themes_methods": 0.10,
        "themes_observations": 0.75,
        "themes_phenomena": 0.10,
        "teachers": ["Lauri Jetsu", "Thomas Hackman"],
        "topics": [
            "History",
            "Atmospheric impact on observations",
            "Optics",
            "Telescopes and Observations",
            "Detectors",
            "CCD-camera",
            "Image processing",
            "Photometry",
            "Polarimetry",
            "Spectroscopy",
            "Astrometry",
            "Modern telescope technology"
        ],
        "prereqs": ["Tähtitieteen perusteet I"],
        "prereqs_other": []
    },
    {
        "code": "FYS2045",
        "name": "Havaitsevan tähtitieteen peruskurssi II",
        "eng_name": "Observational Astronomy II",
        "op": 5,
        "description": "The course covers observational methods and physics of high-energy astrophysics and radio astronomy.",
        "period": [],
        "year": [],
        "content_lectures": 18,
        "content_exercises": 12,
        "content_other": ["9 lab hours", "practical exercise/report", "exam"],
        "themes_theory": 0.20,
        "themes_methods": 0.30,
        "themes_observations": 0.30,
        "themes_phenomena": 0.20,
        "teachers": [],
        "topics": [
            "Radiative processes",
            "Sources of high-energy emission",
            "High energy Observatories",
            "Galaxy clusters are high energies",
            "XSPEC and basics of spectral analysis",
            "DS9 and basics of surface brightness analysis",
            "Radio telescopes",
            "Antennas and receivers",
            "Spectrometers and single-dish observations",
            "Calibration of radio observations",
            "Radio spectroscopy",
            "Continuum observations",
            "Radio interferometry"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2054",
        "name": "Tähtien rakenne ja kehitys",
        "eng_name": "Stellar Structure and Evolution",
        "op": 5,
        "description": "The course provides basic knowledge of stellar physics, structure, energy production, and evolution.",
        "period": [3, 4],
        "year": [2, 3],
        "content_lectures": 13,
        "content_exercises": 5,
        "content_other": ["1 computer exercise", "exam"],
        "themes_theory": 0.60,
        "themes_methods": 0.20,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Thomas Hackman", "Joonas Nättilä"],
        "topics": [
            "Stellar structure equations",
            "Diffusion equation",
            "Convection (Ledoux and Schwarzschild criterion)",
            "Rosseland mean opacity",
            "Ideal gas",
            "Radiation pressure",
            "Blackbody radiation",
            "Degenerate electron gas",
            "Saha equation",
            "Nuclear reactions (formation of elements)",
            "Stellar classification",
            "Star formation",
            "Jeans mass",
            "Stellar evolutionary tracks (protostar, pre-main sequence, main sequence, post-main sequence)",
            "Compact stars (white dwarfs, Chandrasekhar mass, neutron stars, Tolman-Oppenheimer-Volkoff limit, black holes)",
            "Planetary nebulae",
            "Supernova"
        ],
        "prereqs": ["Tähtitieteen perusteet I", "Tähtitieteen perusteet II", "Termofysiikan perusteet"],
        "prereqs_other": []
    },
    {
        "code": "FYS2046",
        "name": "Astrofysiikan peruskurssi I",
        "eng_name": "Basics of Astrophysics I",
        "op": 5,
        "description": "The course covers radiative processes, stellar atmosphere physics, and the passage of radiation through matter.",
        "period": [3],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.75,
        "themes_methods": 0.10,
        "themes_observations": 0.05,
        "themes_phenomena": 0.10,
        "teachers": ["Joonas Nättilä"],
        "topics": [
            "Brief introduction to the history of astrophysics",
            "Radiative processes, definitions",
            "Black-body radiation",
            "Emission and absorption coefficients",
            "Radiative transfer, solutions to basic radiative transfer problems",
            "Solar limb darkening",
            "Gas physics in the solar atmosphere",
            "Maxwell-Boltzmann distribution",
            "Boltzmann equation for atomic excitation",
            "Saha equation for ionisation",
            "Thermodynamic equilibrium",
            "Stellar atmospheric model calculations"
        ],
        "prereqs": [],
        "prereqs_other": ["Basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "FYS2047",
        "name": "Astrofysiikan peruskurssi II",
        "eng_name": "Basics of Astrophysics II",
        "op": 5,
        "description": "The course deepens understanding of interstellar matter, the formation of spectral lines, and the interaction of radiation with matter.",
        "period": [4],
        "year": [2, 3],
        "content_lectures": 12,
        "content_exercises": 6,
        "content_other": ["exam"],
        "themes_theory": 0.50,
        "themes_methods": 0.20,
        "themes_observations": 0.10,
        "themes_phenomena": 0.20,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Extinction, absorption by classic dipole",
            "Scattering by classic dipole",
            "Continuum absorption (dipole, Hydrogen, other elements)",
            "Hydrogen ionisation and recombinations",
            "Transition probabilities",
            "Spectral line emission and absorption; spectral line profiles",
            "Radiative transfer equation",
            "Neutral hydrogen in interstellar space",
            "Continuum emission and absorption in interstellar space"
        ],
        "prereqs": ["Astrofysiikan peruskurssi I"],
        "prereqs_other": ["basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "FYS2043",
        "name": "Johdatus avaruusplasmafysiikkaan",
        "eng_name": "Introduction to Space Plasma Physics",
        "op": 5,
        "description": "The course provides basics of plasma physics and its applications in space physics and astrophysics.",
        "period": [1],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 5,
        "content_other": [],
        "themes_theory": 0.30,
        "themes_methods": 0.10,
        "themes_observations": 0.20,
        "themes_phenomena": 0.40,
        "teachers": ["Emilia Kilpua", "Thomas Hackman", "Taina Kurki-Suonio", "Sanni Hoilijoki", "Kai Nordlund"],
        "topics": [
            "Basics of plasma physics phenomena and theory",
            "Basic phenomena of space plasma physics",
            "Astrophysical plasma phenomena",
            "Fusion in stars",
            "Origin of elements",
            "Magnetic activity of stars",
            "Fusion on Earth",
            "Plasma and materials"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2027",
        "name": "Mekaniikka",
        "eng_name": "Mechanics",
        "op": 5,
        "description": "The course covers classical mechanics, Lagrangian and Hamiltonian formalisms, and their applications.",
        "period": [1],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["7 problem set help sessions", "6 case studies"],
        "themes_theory": 0.75,
        "themes_methods": 0.25,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Mikael Granvik", "Elina Keihänen"],
        "topics": [
            "Dimensional analysis",
            "2-body problem",
            "Newton’s law of universal gravitation",
            "Derivation of Kepler’s laws",
            "Kepler equation",
            "Lagrangian formalism",
            "Variational calculus",
            "Principle of least action",
            "Lagrangian equations of motion",
            "Symmetries in Lagrangian formalism",
            "Coupled oscillators",
            "Dynamics of rigid bodies",
            "Transitions between rotating and inertial frames",
            "Hamiltonian mechanics",
            "Hamilton’s equations of motion",
            "Canonical transformations"
        ],
        "prereqs": ["Fysiikan matemaattiset menetelmät IIb"],
        "prereqs_other": ["Basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills", "basic skills in numerics"]
    },
    {
        "code": "FYS2055",
        "name": "Taivaanmekaniikka",
        "eng_name": "Celestial Mechanics",
        "op": 5,
        "description": "The course delves into the movements of celestial bodies, orbital mechanics, and perturbation theory.",
        "period": [2],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["7 problem set help sessions", "6 case studies"],
        "themes_theory": 0.40,
        "themes_methods": 0.40,
        "themes_observations": 0.0,
        "themes_phenomena": 0.20,
        "teachers": ["Mikael Granvik"],
        "topics": [
            "Applications of the 2-body problem",
            "Perturbation theory",
            "N-body problem",
            "Numerical integrators",
            "3-body problem theory",
            "Applications of 3-body problem",
            "Disturbing function",
            "Orbit computation"
        ],
        "prereqs": ["Mekaniikka", "Fysiikan matemaattiset menetelmät IIa"],
        "prereqs_other": ["basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills", "basic skills in scientific programming"]
    },
    {
        "code": "FYS2051",
        "name": "Aurinkokunnan fysiikka",
        "eng_name": "Solar System Physics",
        "op": 5,
        "description": "The course covers the physics, formation, and observation of solar system bodies.",
        "period": [3, 4],
        "year": [2, 3],
        "content_lectures": 12,
        "content_exercises": 5,
        "content_other": ["presentation", "3 essays (1/3 mandatory)", "programming project", "home exam"],
        "themes_theory": 0.50,
        "themes_methods": 0.10,
        "themes_observations": 0.20,
        "themes_phenomena": 0.20,
        "teachers": ["Anne Virkki"],
        "topics": [
            "Solar System objects",
            "Solar System formation theories",
            "Planetary geophysical processes (heat, radiation, petrophysics, atmospheres, oceans)",
            "(Planetary) radiation quantities (intensity, flux density, luminosity, magnitudes)",
            "Reflectivity, albedos, and integrated brightness of planetary bodies",
            "Observation methods (photometry, spectroscopy, polarimetry and their combinations)",
            "Empirical and analytical scattering laws",
            "HG / HG1G2 / HG12 systems",
            "Multiwavelength observations of Solar System objects from UV to radio",
            "Fundamental light scattering concepts (Stokes, scattering matrix, scattering quantities)",
            "Exoplanet observations",
            "Requirements of (extraterrestrial) life",
            "Spacecraft missions for planetary exploration",
            "Presenting scientific information in written and oral forms, reference critique",
            "Numerical implementation of integrated brightness for discretised spheroids"
        ],
        "prereqs": ["Tähtitieteen perusteet I", "Tähtitieteen perusteet II", "Tieteellinen laskenta I", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Matemaattiset apuneuvot III"],
        "prereqs_other": []
    },
    {
        "code": "FYS2052",
        "name": "Galaksit ja kosmologia",
        "eng_name": "Galaxies and Cosmology",
        "op": 5,
        "description": "The course gives an overview of the structure, dynamics, and formation of galaxies, as well as the basics of cosmology.",
        "period": [1, 2],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.70,
        "themes_methods": 0.15,
        "themes_observations": 0.05,
        "themes_phenomena": 0.10,
        "teachers": ["Peter Johansson"],
        "topics": [
            "Introduction to galaxies. Galaxy classification, stellar populations and the interstellar medium.",
            "Galactic dynamics: Poisson equation, virial theorem, relaxation timescales, Boltzmann equation and phase-space.",
            "Cosmology: FRW-metric, angular-diameter and luminosity distances, Friedmann equations and their solutions",
            "The age of the Universe. Dark matter and dark energy. Elliptical galaxies.",
            "Spiral galaxies and lenticular galaxies.",
            "Active galaxies and supermassive black holes. The Local Group of galaxies.",
            "Galaxy clusters and the large-scale structure of the Universe. The early Universe, inflation theory and the formation of structure.",
            "Galaxy formation and evolution, a theoretical framework."
        ],
        "prereqs": [],
        "prereqs_other": ["Basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "FYS2053",
        "name": "Linnunradan rakenne",
        "eng_name": "Structure of the Milky Way",
        "op": 5,
        "description": "The course examines the structure, kinematics, and dynamics of the Milky Way, as well as the distribution of interstellar matter.",
        "period": [1, 2],
        "year": [2, 3],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.45,
        "themes_methods": 0.10,
        "themes_observations": 0.40,
        "themes_phenomena": 0.05,
        "teachers": ["Peter Johansson", "Jorma Harju"],
        "topics": [
            "Introduction to the Milky Way",
            "Observing the distances and velocities of stars in the Milky Way",
            "Interstellar dust and extinction",
            "Stellar statistics",
            "Structure of the Milky Way: Stellar and gaseous disc, stellar bulge, stellar halo, central supermassive black hole, dark matter halo",
            "GAIA satellite: Revolutionising the study of the Milky Way. Stellar kinematics in the Milky Way",
            "Galactic rotation. The Oort constants. The Solar orbit and the orbits of other stars in the Milky Way",
            "The Milky Way rotation curve and spiral structure. The mass density in the vicinity of the Sun",
            "Formation and evolution of the Milky Way"
        ],
        "prereqs": [],
        "prereqs_other": ["Basic courses in astronomy", "basic courses in physics", "basic studies in theoretical physics or corresponding mathematical skills"]
    },
    {
        "code": "BSPH2009",
        "name": "Basics of Astronomy I",
        "eng_name": "Basics of Astronomy I",
        "op": 5,
        "description": "General overview of astronomy basics (English Bachelor's programme equivalent).",
        "period": [],
        "year": [],
        "content_lectures": 26,
        "content_exercises": 6,
        "content_other": ["exam"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Finoguenov + everyone"],
        "topics": [
            "Spherical Astronomy",
            "Observational methods I, II",
            "Facilities",
            "Radiative processes I, II",
            "Stellar spectra, structure, evolution",
            "ISM and SF",
            "Variable and binary stars",
            "Compact objects",
            "SN nucleosynthesis and chemical enrichment models"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2081",
        "name": "Cosmology I",
        "eng_name": "Cosmology I",
        "op": 5,
        "description": "Introduction to the standard model of cosmology, Friedmann-Robertson-Walker universe, and early universe physics.",
        "period": [1, 2],
        "year": [3],
        "content_lectures": 28,
        "content_exercises": 12,
        "content_other": ["Exam"],
        "themes_theory": 0.80,
        "themes_methods": 0.10,
        "themes_observations": 0.10,
        "themes_phenomena": 0.0,
        "teachers": ["Hannu Kurki-Suonio"],
        "topics": [
            "The homogeneous and isotropic universe",
            "Friedmann equations",
            "Thermal history of the universe",
            "Big Bang Nucleosynthesis",
            "Dark matter and Dark energy",
            "Inflation"
        ],
        "prereqs": ["Galaksit ja kosmologia"],
        "prereqs_other": []
    },
    {
        "code": "PAP301",
        "name": "Seminar in Particle Physics and Astrophysical Sciences",
        "eng_name": "Seminar in Particle Physics and Astrophysical Sciences",
        "op": 5,
        "description": "Develop your oral and peer review skills, develop your ability to promote your expertise and market yourself, help with the MSc thesis project.",
        "period": [1, 2, 3, 4],
        "year": [4, 5],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["MSc thesis plan", "MSc thesis disposition", "Career development tasks", "Oral presentation", "Opponent to other presentations"],
        "themes_theory": 0.0,
        "themes_methods": 1.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Kenneth Österberg"],
        "topics": [
            "MSc thesis plan",
            "MSc thesis disposition",
            "Career development",
            "Scientific presentation skills",
            "Peer review"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP350",
        "name": "Master's Thesis",
        "eng_name": "Master's Thesis",
        "op": 30,
        "description": "Master's thesis work.",
        "period": [],
        "year": [5],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Independent study"],
        "themes_theory": 0.0,
        "themes_methods": 1.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": [],
        "topics": [
            "Independent research",
            "Scientific writing"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP399",
        "name": "MSc Maturity Test",
        "eng_name": "MSc Maturity Test",
        "op": 0,
        "description": "Maturity test for the Master's degree.",
        "period": [],
        "year": [5],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": [],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP302",
        "name": "Open Problems in Modern Astrophysics",
        "eng_name": "Open Problems in Modern Astrophysics",
        "op": 5,
        "description": "The student will familiarize him/herself with seven exciting hot topics in contemporary astrophysics, learn to read review papers and specialised research articles, and learn to discuss research articles.",
        "period": [1, 2],
        "year": [4],
        "content_lectures": 14,
        "content_exercises": 7,
        "content_other": ["7 problem set discussion sessions", "exam"],
        "themes_theory": 0.15,
        "themes_methods": 0.05,
        "themes_observations": 0.15,
        "themes_phenomena": 0.65,
        "teachers": ["Peter Johansson", "Till Sawala"],
        "topics": [
            "The detection and properties of Extrasolar planets",
            "Gamma-ray Bursts: Observation and Theory",
            "Stellar dynamics near massive black holes and gravitational waves",
            "The formation and evolution of star clusters",
            "Nearby dwarf galaxies: testing the limits of structure formation",
            "Massive galaxies at high redshifts – a challenge for structure formation?",
            "Dark Energy and the Hubble tension"
        ],
        "prereqs": [],
        "prereqs_other": ["Bachelor studies in astronomy or equivalent"]
    },
    {
        "code": "PAP303",
        "name": "Statistical Inverse Methods",
        "eng_name": "Statistical Inverse Methods",
        "op": 5,
        "description": "You will learn advanced statistical methods to describe and analyze research data, theory and practice of statistical estimation and testing, multivariate methods, Monte Carlo statistical techniques, Bayesian inference, and statistical inversion using Markov Chain Monte Carlo methods.",
        "period": [3, 4],
        "year": [4],
        "content_lectures": 12,
        "content_exercises": 12,
        "content_other": ["home exam"],
        "themes_theory": 0.0,
        "themes_methods": 1.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Antti Penttilä"],
        "topics": [
            "Distributions",
            "Statistical inference",
            "Statistical tests",
            "Linear model",
            "Non-linear model",
            "Non-parametric methods",
            "Multivariate methods",
            "Bayesian inference",
            "Monte Carlo methods",
            "Markov chain Monte Carlo",
            "Artificial neural networks"
        ],
        "prereqs": ["Tieteellinen laskenta I", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Matemaattiset apuneuvot III", "Havaintojen tilastollinen käsittely"],
        "prereqs_other": []
    },
    {
        "code": "PAP304",
        "name": "Plasma Physics",
        "eng_name": "Plasma Physics",
        "op": 5,
        "description": "You will obtain solid knowledge of basic concepts and phenomena of plasma physics, skills to analytically solve basic problems, and skills to derive various basic plasma equations.",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 13,
        "content_exercises": 6,
        "content_other": [],
        "themes_theory": 0.70,
        "themes_methods": 0.0,
        "themes_observations": 0.10,
        "themes_phenomena": 0.20,
        "teachers": ["Minna Palmroth"],
        "topics": [
            "Basic plasma parameters",
            "Single particle motion",
            "Kinetic plasma description",
            "Macroscopic plasma description",
            "MHD waves",
            "Cold plasma waves"
        ],
        "prereqs": [],
        "prereqs_other": ["Basic physics courses", "Solid calculation skills", "Good knowledge on electrodynamics"]
    },
    {
        "code": "PAP323",
        "name": "Advanced Space Plasma Physics",
        "eng_name": "Advanced Space Plasma Physics",
        "op": 10,
        "description": "You will be able to navigate the terminology and idiosyncrasies of space physics publications, derive different mathematical approaches to plasma physics from first principles, and discern which of these approaches are applicable for a given physical problem.",
        "period": [3, 4],
        "year": [5],
        "content_lectures": 24,
        "content_exercises": 12,
        "content_other": [],
        "themes_theory": 0.70,
        "themes_methods": 0.10,
        "themes_observations": 0.0,
        "themes_phenomena": 0.20,
        "teachers": ["Urs Ganse"],
        "topics": [
            "Detailed particle motion in EM fields, current sheets",
            "Galactic Cosmic Rays and Solar Energetic Particles",
            "Wave propagation in dielectric and stratified media",
            "Vlasov theory and Landau damping",
            "MHD (force-free fields and flux ropes)",
            "Plasma instabilities",
            "Collisionless shock waves",
            "Magnetic reconnection",
            "Solar dynamo",
            "Radiation and scattering",
            "Transport (Fokker-Planck theory)"
        ],
        "prereqs": ["Plasma Physics", "Elektrodynamiikka I", "Elektrodynamiikka II", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Fysiikan matemaattiset menetelmät Ia", "Fysiikan matemaattiset menetelmät Ib", "Fysiikan matemaattiset menetelmät IIa", "Fysiikan matemaattiset menetelmät IIb"],
        "prereqs_other": ["thermodynamics/statistical physics"]
    },
    {
        "code": "PAP324",
        "name": "Numerical Space Physics",
        "eng_name": "Numerical Space Physics",
        "op": 5,
        "description": "You will learn about the various simulation methods that are used in space physics, learn hands-on what running a simulation entails, and understand the principles behind the numerical methods.",
        "period": [4],
        "year": [5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["practical hands-on exercises"],
        "themes_theory": 0.50,
        "themes_methods": 0.10,
        "themes_observations": 0.0,
        "themes_phenomena": 0.40,
        "teachers": ["Jens Pomoell", "Daniel Price"],
        "topics": [
            "Simulation methods in space physics",
            "Running simulations and analysing the output",
            "Principles of numerical methods (focus on MHD)"
        ],
        "prereqs": ["Plasma Physics", "Tieteellinen laskenta I", "Tieteellinen laskenta II"],
        "prereqs_other": ["Basic programming skills in Python/Matlab"]
    },
    {
        "code": "PAP321",
        "name": "Solar Physics",
        "eng_name": "Solar Physics",
        "op": 5,
        "description": "You will learn about the history of formation of the Sun and its future evolution, understand the processes of energy production and transfer, and learn about current and past solar space missions.",
        "period": [3],
        "year": [5],
        "content_lectures": 12,
        "content_exercises": 3,
        "content_other": ["student seminar"],
        "themes_theory": 0.40,
        "themes_methods": 0.20,
        "themes_observations": 0.0,
        "themes_phenomena": 0.40,
        "teachers": ["Ranadeep Sarkar", "Eleanna Asvestari", "Simon Good"],
        "topics": [
            "Formation and evolution of the Sun and Solar System",
            "Standard solar model",
            "Solar atmosphere",
            "Solar oscillations and helioseismology",
            "Convection and solar rotation",
            "Solar dynamo and solar cycle",
            "Solar wind",
            "Solar eruptions"
        ],
        "prereqs": [],
        "prereqs_other": ["Calculus", "linear algebra", "knowledge of mechanics and electromagnetism"]
    },
    {
        "code": "PAP305",
        "name": "Space Applications of Plasma Physics",
        "eng_name": "Space Applications of Plasma Physics",
        "op": 5,
        "description": "You will obtain solid understanding of space physics, basic solar physics, solid theoretical knowledge behind key phenomena in space plasma physics, and skills to analyse key data sets.",
        "period": [2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["practical hands-on exercises"],
        "themes_theory": 0.20,
        "themes_methods": 0.70,
        "themes_observations": 0.0,
        "themes_phenomena": 0.10,
        "teachers": ["Eleanna Asvestari", "Lucile Turc"],
        "topics": [
            "Basics of the Sun, its atmosphere",
            "Solar wind and interplanetary shocks",
            "Earth’s magnetosphere and ionosphere",
            "Magnetospheric storms and substorms",
            "Space weather",
            "Key data sets in space physics"
        ],
        "prereqs": ["Elektrodynamiikka I", "Elektrodynamiikka II", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Fysiikan matemaattiset menetelmät Ia", "Fysiikan matemaattiset menetelmät Ib", "Fysiikan matemaattiset menetelmät IIa", "Fysiikan matemaattiset menetelmät IIb"],
        "prereqs_other": ["Basic physics courses"]
    },
    {
        "code": "PAP354",
        "name": "Space and Astrophysical Plasma Turbulence",
        "eng_name": "Space and Astrophysical Plasma Turbulence",
        "op": 5,
        "description": "The course covers the theory and phenomena of plasma turbulence in space and astrophysics.",
        "period": [2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 3,
        "content_other": ["2 computer exercises", "seminar", "exam"],
        "themes_theory": 0.70,
        "themes_methods": 0.10,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Simon Good", "Joonas Nättilä"],
        "topics": [
            "MHD equations",
            "Hydrodynamical (Kolmogorov) turbulence",
            "Weak wave turbulence",
            "Strong MHD Turbulence",
            "Intermittency",
            "Fermi-II particle acceleration mechanism"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP306",
        "name": "Advanced Course in Observational Astronomy I",
        "eng_name": "Advanced Course in Observational Astronomy I",
        "op": 5,
        "description": "Participants of the course will learn about preparation, conduction and data reduction of modern astronomical observations.",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["20 hours observing during intense week", "individual report"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov"],
        "topics": [
            "Principles of optical imaging and spectroscopy",
            "Telescopes: mounts, hardware and operations",
            "Nordic Optical Telescope and NOT fellows",
            "NOT Telescope Control System and its commands",
            "ALFOSC/NOT operation manual",
            "Preparation for the observations and observing tools",
            "Project introduction and target preparation, finding chats and upload",
            "Project science and its requirements on observations and data reduction",
            "Observing guide and tips",
            "Remote observing tools and preparation of NOT Observational Blocks",
            "NOTCam and its commands",
            "Preparation for observations at Turku"
        ],
        "prereqs": ["Havaitsevan tähtitieteen peruskurssi I", "Tähtitieteen perusteet I"],
        "prereqs_other": []
    },
    {
        "code": "PAP307",
        "name": "Advanced Course in Observational Astronomy II",
        "eng_name": "Advanced Course in Observational Astronomy II",
        "op": 5,
        "description": "The students should be able to identify and extract raw data from ESO Science Archive, reduce these data using a relevant pipeline provided by ESO, and carry out an analysis of complex spectroscopic data.",
        "period": [4],
        "year": [4, 5],
        "content_lectures": 24,
        "content_exercises": 0,
        "content_other": ["intense week in Turku", "4 assignments"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov"],
        "topics": [
            "ESO instrumentation on Paranal and future developments on Armazones",
            "ALMA: telescopes, operations, data reduction",
            "4MOST/VISTA facility and observing tools",
            "VLT data analysis using selected instruments: KMOS, MUSE, UVES, XSHOOTER, SoX",
            "ESO proposal writing",
            "VST and data analysis",
            "JWST and data analysis",
            "Euclid and its data repository",
            "Data visualization tools",
            "ESO data archive"
        ],
        "prereqs": ["PAP306", "PAP308"],
        "prereqs_other": ["Basic and fundamental observational astronomy courses"]
    },
    {
        "code": "PAP308",
        "name": "Special Course in Observational Astronomy",
        "eng_name": "Special Course in Observational Astronomy",
        "op": 5,
        "description": "The students will learn how to reduce their data obtained in Advanced Observational Astronomy course and learn the general principles of modern astronomical data reduction.",
        "period": [1, 2],
        "year": [4, 5],
        "content_lectures": 24,
        "content_exercises": 0,
        "content_other": ["24 hours of practical work", "presentation"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov", "Clif Kirkpatrick"],
        "topics": [
            "IRAF installation",
            "Optical imaging reduction",
            "Bias and bias subtraction",
            "Sensitivity and using sky/dome flats",
            "Optical spectral reduction",
            "Basic processing steps",
            "Tracing the spectrum",
            "Identification of the spectral features and redshift measurement",
            "NIR image reduction and spectroscopy",
            "Software servers at Turku and remote data analysis",
            "Preparation for observations",
            "Calibrations during the night and data retrieval",
            "NOT data processing"
        ],
        "prereqs": [],
        "prereqs_other": ["Fundamental and Basic Observational Astronomy courses"]
    },
    {
        "code": "PAP309",
        "name": "Interstellar Matter",
        "eng_name": "Interstellar Matter",
        "op": 5,
        "description": "You will know the chemical and physical composition of the interstellar medium, understand the principles that determine the physical state of the ISM, and learn the main steps of the star-formation process.",
        "period": [2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 4,
        "content_other": ["report work", "exam"],
        "themes_theory": 0.30,
        "themes_methods": 0.20,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Observations of the interstellar medium",
            "Stability and structure of interstellar clouds",
            "Collapse of cloud cores and protostellar evolution",
            "High-mass star formation",
            "Astrochemistry"
        ],
        "prereqs": ["Havaitsevan tähtitieteen peruskurssi II"],
        "prereqs_other": ["Astrofysiikan peruskurssi I-II"]
    },
    {
        "code": "PAP311",
        "name": "Small Bodies in the Solar System",
        "eng_name": "Small Bodies in the Solar System",
        "op": 5,
        "description": "The student is able to read and understand scientific literature, can discuss scientific articles, and understands the major research topics in small-body research.",
        "period": [1, 2],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["13 help sessions", "13 learning logs", "13 self-assessments", "exam"],
        "themes_theory": 0.20,
        "themes_methods": 0.10,
        "themes_observations": 0.30,
        "themes_phenomena": 0.40,
        "teachers": ["Mikael Granvik", "Eric MacLennan"],
        "topics": [
            "Asteroid surveys and populations",
            "Asteroid astrometry and orbits",
            "Asteroid photometry and rotations",
            "Asteroid shapes",
            "Asteroid spectroscopy and surface composition",
            "Yarkovsky and YORP effects",
            "Thermal-infrared observations and thermophysical modeling",
            "Asteroid systems",
            "Asteroid families",
            "Active asteroids and meteors",
            "Asteroid formation, and dynamical and collisional evolution",
            "Transneptunian objects and Oort-cloud objects",
            "Centaurs and comets"
        ],
        "prereqs": ["FYS2027", "FYS2055", "FYS2051"],
        "prereqs_other": []
    },
    {
        "code": "PAP312",
        "name": "Time Series Analysis in Astronomy",
        "eng_name": "Time Series Analysis in Astronomy",
        "op": 5,
        "description": "The students will learn the theory, the application and the programming of different period finding methods that can be used to analyse astronomical data.",
        "period": [1],
        "year": [5],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["Assignment(-s) each week"],
        "themes_theory": 0.05,
        "themes_methods": 0.85,
        "themes_observations": 0.05,
        "themes_phenomena": 0.05,
        "teachers": ["Lauri Jetsu"],
        "topics": [
            "Python coding",
            "Discrete Chi-square Method (DCM)",
            "Discrete Fourier Transform (DFT)",
            "DCM: Theory, programming, application",
            "DCM and DFT application to simulated data",
            "DCM and DFT performance comparison",
            "Time Series Analysis, Simulation of astrophysical data, Linear and non-linear models",
            "Multiperiodicity, DFT pre-whitening, De-trending, Bootstrap, Fisher-test, Nested models"
        ],
        "prereqs": ["Tieteellinen laskenta I"],
        "prereqs_other": ["equivalent Python programming skills"]
    },
    {
        "code": "PAP313",
        "name": "Variable Stars",
        "eng_name": "Variable Stars",
        "op": 5,
        "description": "Previously unpublished photometry of a chromospherically active star is analysed with different period analysis methods, and detailed modelling of the light curves is performed.",
        "period": [1, 2],
        "year": [5],
        "content_lectures": 14,
        "content_exercises": 0,
        "content_other": ["Assignment(-s) each week"],
        "themes_theory": 0.05,
        "themes_methods": 0.70,
        "themes_observations": 0.15,
        "themes_phenomena": 0.10,
        "teachers": ["Lauri Jetsu"],
        "topics": [
            "Discrete Chi-square Method (DCM)",
            "Discrete Fourier Transform (DFT)",
            "DCM and DFT applications to real variable star data",
            "DCM: theory, programming and application",
            "DCM and DFT performance comparison",
            "DCM predictive multiperiodic models: theory and application",
            "Python coding",
            "Chromospherically active stars: Differential rotation, active longitudes, activity cycles",
            "Binary star O-C data: Light time effect, Applegate effect, Apsidal motion, Mass transfer"
        ],
        "prereqs": ["Tieteellinen laskenta I"],
        "prereqs_other": ["equivalent Python programming skills"]
    },
    {
        "code": "PAP351",
        "name": "Stellar magnetic activity",
        "eng_name": "Stellar magnetic activity",
        "op": 5,
        "description": "The student will have a basic understanding of the physical processes behind stellar magnetic activity, different approaches of modelling, and observational methods used for research in this field.",
        "period": [3, 4],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["exam"],
        "themes_theory": 0.30,
        "themes_methods": 0.20,
        "themes_observations": 0.20,
        "themes_phenomena": 0.30,
        "teachers": ["Thomas Hackman"],
        "topics": [
            "Basic MHD concepts",
            "Solar and stellar dynamos",
            "Numerical dynamo simulations",
            "Manifestations of solar and stellar magnetic activity",
            "Solar/stellar corona and winds",
            "Star-planet magnetic interaction",
            "Observing solar and stellar magnetic activity",
            "Inversion methods (Doppler imaging, photometric inversion)"
        ],
        "prereqs": ["Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Matemaattiset apuneuvot III", "Tieteellinen laskenta I", "PAP304", "PAP303", "PAP354", "FYS2041", "FYS2042", "FYS2054"],
        "prereqs_other": ["Basic physics courses"]
    },
    {
        "code": "PAP314",
        "name": "Introduction to light scattering",
        "eng_name": "Introduction to light scattering",
        "op": 5,
        "description": "During the course, the student will become familiar with the concepts of electromagnetic scattering and will learn how to use existing computer codes in astronomical and atmospheric applications.",
        "period": [4],
        "year": [3, 4],
        "content_lectures": 14,
        "content_exercises": 5,
        "content_other": ["project task", "home exam"],
        "themes_theory": 0.60,
        "themes_methods": 0.20,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Karri Muinonen", "Antti Penttilä", "Anne Virkki", "Yehor Surkov", "Zuri Gray"],
        "topics": [
            "Introduction to scattering",
            "Scattering at a planar interface",
            "Mie scattering",
            "Ray optics",
            "Angular scattering",
            "Rayleigh scattering",
            "Effective medium approximations",
            "Rayleigh-Gans scattering",
            "Transition matrix method (T-matrix method)",
            "Radar scattering",
            "Applications"
        ],
        "prereqs": ["Tieteellinen laskenta I", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Matemaattiset apuneuvot III"],
        "prereqs_other": ["Electrodynamics I", "Electrodynamics II", "Theoretical astrophysics package"]
    },
    {
        "code": "PAP315",
        "name": "Computational light scattering",
        "eng_name": "Computational light scattering",
        "op": 5,
        "description": "The course offers an introduction and theoretical foundation for elastic electromagnetic scattering by arbitrary objects, with main emphasis on spherical particles and Mie scattering.",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 5,
        "content_other": ["2 project tasks", "home exam"],
        "themes_theory": 0.40,
        "themes_methods": 0.40,
        "themes_observations": 0.0,
        "themes_phenomena": 0.20,
        "teachers": ["Karri Muinonen", "Antti Penttilä", "Anne Virkki", "Yehor Surkov", "Zuri Gray"],
        "topics": [
            "Introduction to single scattering",
            "Scattering by a spherical particle (Mie scattering)",
            "Discrete-dipole approximation, volume-integral equation",
            "Discrete-dipole approximation, particle near a surface",
            "T-matrix method",
            "Ray optics approximation",
            "Introduction to multiple scattering (radiative transfer and coherent backscattering)",
            "Monte Carlo methods for multiple scattering",
            "Superposition T-matrix method",
            "Rough-surface scattering modeling",
            "Radar scattering",
            "Geometric optics for close-packed media"
        ],
        "prereqs": ["PAP314"],
        "prereqs_other": ["Electrodynamics I", "Electrodynamics II", "Tieteellinen laskenta I", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Matemaattiset apuneuvot III"]
    },
    {
        "code": "PAP316",
        "name": "Astrophysical light scattering problems",
        "eng_name": "Astrophysical light scattering problems",
        "op": 5,
        "description": "The course offers an introduction and theoretical foundation for elastic electromagnetic scattering by complex random media of particles (multiple scattering).",
        "period": [4],
        "year": [3, 4],
        "content_lectures": 14,
        "content_exercises": 3,
        "content_other": ["2 inverse methods project tasks", "home exam"],
        "themes_theory": 0.25,
        "themes_methods": 0.20,
        "themes_observations": 0.25,
        "themes_phenomena": 0.10,
        "teachers": ["Karri Muinonen", "Antti Penttilä", "Anne Virkki", "Yehor Surkov", "Zuri Gray"],
        "topics": [
            "Introduction to photometry, polarimetry, and spectrometry",
            "Experimental scattering measurements",
            "Polarimetry, photometry, and spectrometry of the Moon",
            "Mercury, Venus, Mars",
            "Asteroids",
            "Interplanetary dust",
            "Comets",
            "Icy moons of outer planets, Saturn’s rings",
            "Transneptunian objects",
            "Interstellar dust",
            "Exoplanets"
        ],
        "prereqs": ["PAP314"],
        "prereqs_other": ["Electrodynamics I", "Electrodynamics II", "Tieteellinen laskenta I", "Matemaattiset apuneuvot I", "Matemaattiset apuneuvot II", "Matemaattiset apuneuvot III"]
    },
    {
        "code": "PAP317",
        "name": "Galactic dynamics",
        "eng_name": "Galactic dynamics",
        "op": 5,
        "description": "The student will be able to calculate relaxation and dynamical timescales, gravitational potential, describe orbits, and understand Boltzmann and Jeans equations in galaxy dynamics.",
        "period": [3, 4],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.75,
        "themes_methods": 0.15,
        "themes_observations": 0.05,
        "themes_phenomena": 0.05,
        "teachers": ["Peter Johansson"],
        "topics": [
            "Introduction to galactic dynamics",
            "Potential theory",
            "The Milky Way potential and Poisson solvers",
            "Orbits in static spherical potentials",
            "Orbits in axisymmetric and non-axisymmetric potentials",
            "Numerical orbit integration",
            "The collisionless Boltzmann equation",
            "Distribution functions for spherical isotropic and anisotropic systems",
            "Jeans and virial equations",
            "Stellar kinematics as a mass detector: Black holes and dark matter",
            "Choice of equilibrium and chaotic dynamics",
            "Stability of collisionless systems",
            "Disk dynamics and spiral structure",
            "Kinetic theory and relaxation processes",
            "Mergers of galaxies and galaxy formation"
        ],
        "prereqs": ["FYS2055", "FYS2052"],
        "prereqs_other": ["Bachelor studies in astronomy or equivalent", "Basic and intermediate-level courses of Astronomy", "Analytical Mechanics", "FYMM I-II"]
    },
    {
        "code": "PAP318",
        "name": "Galaxy formation and evolution",
        "eng_name": "Galaxy formation and evolution",
        "op": 5,
        "description": "The student will learn to understand galaxy formation as a process, master Newtonian perturbation theory, and understand the role of dark matter and feedback in galaxy evolution.",
        "period": [1, 2],
        "year": [4, 5],
        "content_lectures": 14,
        "content_exercises": 6,
        "content_other": ["7 problem set help sessions", "exam"],
        "themes_theory": 0.70,
        "themes_methods": 0.10,
        "themes_observations": 0.15,
        "themes_phenomena": 0.05,
        "teachers": ["Peter Johansson"],
        "topics": [
            "Introduction to galaxy formation and overview",
            "Observations of galaxies",
            "Cosmology overview",
            "Linear evolution of small density perturbations",
            "Jeans instabilities and horizons in an expanding Universe",
            "Baryonic and dark matter models of galaxy formation",
            "Correlation functions and the spectrum of the initial fluctuations",
            "Non-linear evolution of dark matter haloes",
            "Formation and evolution of gaseous haloes",
            "Star formation and stellar feedback in galaxies",
            "Formation of disk galaxies",
            "Galaxy interactions and transformations",
            "Formation of elliptical galaxies",
            "Formation of active galaxies and the physics of supermassive black holes"
        ],
        "prereqs": ["FYS2052", "FYS2053", "FYS2046"],
        "prereqs_other": ["Bachelor studies in astronomy or equivalent", "Cosmology I", "FYMM I-II"]
    },
    {
        "code": "PAP319",
        "name": "High Energy Astrophysics",
        "eng_name": "High Energy Astrophysics",
        "op": 5,
        "description": "The students obtain the knowledge of the emission processes and particle acceleration mechanisms important for high-energy astrophysics and learn how to reduce modern high-energy observations.",
        "period": [1, 2],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 0,
        "content_other": ["24 hours of lab work", "grade based on labs"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": ["Alexis Finoguenov"],
        "topics": [
            "Radiative processes",
            "Sources of high-energy emission and their models",
            "Particle acceleration",
            "High energy Observatories",
            "Galaxy clusters are high energies",
            "Hydrostatic Equilibrium and mass estimates",
            "XMM-Newton data reduction",
            "High energy emission from accreting black holes",
            "Statical tools for the analysis of high-energy spectra",
            "High energy data repositories and software",
            "Spectral simulations, and mission forecasts, proposal tools",
            "Quantum electrodynamic processes at high energies",
            "X-IFU/Athena forecasts"
        ],
        "prereqs": [],
        "prereqs_other": ["Basic observational astronomy", "Physics courses"]
    },
    {
        "code": "PAP320",
        "name": "Radiative Transfer",
        "eng_name": "Radiative Transfer",
        "op": 5,
        "description": "You will learn how microphysical properties of the medium link to macroscopic radiative transport, understand common approximations, and use existing radiative-transfer programs.",
        "period": [1],
        "year": [4, 5],
        "content_lectures": 12,
        "content_exercises": 4,
        "content_other": ["report work", "exam"],
        "themes_theory": 0.30,
        "themes_methods": 0.50,
        "themes_observations": 0.10,
        "themes_phenomena": 0.10,
        "teachers": ["Mika Juvela"],
        "topics": [
            "Radiative transfer equation",
            "Setup of radiative transfer models",
            "Basic radiative transfer methods (ray tracing and Monte Carlo)",
            "Continuum radiative transfer",
            "Dust physics and temperature calculation, stochastic heating",
            "Improvements of the Monte Carlo method",
            "Line radiative transfer",
            "Approximate solutions",
            "Exact solutions with ray tracing and Monte Carlo",
            "Radiative transfer in multiphysics models",
            "Model discretisations (spatial, angular, and frequency grids)",
            "Parallel radiative transfer"
        ],
        "prereqs": ["FYS2010", "FYS2011", "FYS2012", "FYS2013"],
        "prereqs_other": ["Basic programming skills"]
    },
    {
        "code": "PAP352",
        "name": "Galaxy Survey Cosmology",
        "eng_name": "Galaxy Survey Cosmology",
        "op": 5,
        "description": "Large scale galaxy surveys are the main observational tools to advance cosmology; the course focuses on the distribution of galaxies.",
        "period": [3],
        "year": [4, 5],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Four hours of lectures and written problem sets every week"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Hannu Kurki-Suonio"],
        "topics": [],
        "prereqs": ["FYS2081", "PAP326", "FYS2010", "FYS2011", "FYS2012"],
        "prereqs_other": []
    },
    {
        "code": "PAP353",
        "name": "Gravitational Lensing",
        "eng_name": "Gravitational Lensing",
        "op": 5,
        "description": "The course gives the theoretical basis to understand gravitational lensing as a physical phenomenon and its use in extracting cosmological information.",
        "period": [],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["4 hours of lectures/week", "weekly homework problems"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Elina Keihänen"],
        "topics": [
            "Propagation of light in general relativity",
            "Lensing geometry and basic concepts",
            "Weak and strong lensing",
            "Magnification and distortion",
            "Relation to observations",
            "Lensing as a cosmological probe",
            "Shear field, E- and B-modes",
            "Lensing spectrum and correlation function",
            "Shear as a spin-2 field"
        ],
        "prereqs": ["FYS2081", "PAP348"],
        "prereqs_other": ["Fymm 1-2a", "Or equivalent knowledge", "Cosmology II", "Cosmological Perturbation Theory"]
    }
]


additional_courses = [
    {
        "code": "MATR322",
        "name": "Numerical Methods in Scientific Computing",
        "eng_name": "Numerical Methods in Scientific Computing",
        "op": 5,
        "description": "Description not found in curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1010",
        "name": "Matemaattiset apuneuvot I",
        "eng_name": "Mathematical Methods I",
        "op": 5,
        "description": "The course deals with vector calculus, power series, and differential and integral calculus.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Vector calculus",
            "Power series",
            "Differential calculus",
            "Integral calculus"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1011",
        "name": "Matemaattiset apuneuvot II",
        "eng_name": "Mathematical Methods II",
        "op": 5,
        "description": "The course covers the basics of complex numbers, differential equations, and linear algebra.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Basics of complex numbers and functions",
            "Basics of ordinary differential equations (integrating factor, trial function, separability)",
            "Basics of linear algebra"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1012",
        "name": "Matemaattiset apuneuvot III",
        "eng_name": "Mathematical Methods III",
        "op": 5,
        "description": "The course deals with differential and integral calculus of vector functions.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Differential calculus of vector functions: space curves, gradient, divergence, curl",
            "Integral calculus of vector functions: line, surface and volume integrals",
            "Gauss's and Stokes's theorems"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2010",
        "name": "Fysiikan matemaattiset menetelmät Ia",
        "eng_name": "Mathematical Methods for Physicists Ia",
        "op": 5,
        "description": "The course deepens the theory of complex numbers and functions, as well as series expansions.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Complex numbers in depth and their functions",
            "Line integral of a complex function",
            "Series expansions of complex functions (Taylor and Laurent series)",
            "Residue calculus"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2011",
        "name": "Fysiikan matemaattiset menetelmät Ib",
        "eng_name": "Mathematical Methods for Physicists Ib",
        "op": 5,
        "description": "The course covers analytic continuation, special functions, and integral transforms.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Analytic continuation",
            "Special functions (Gamma, beta functions)",
            "Series expansions (asymptotic series and Fourier series)",
            "Fourier and Laplace transforms",
            "Dirac delta"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2012",
        "name": "Fysiikan matemaattiset menetelmät IIa",
        "eng_name": "Mathematical Methods for Physicists IIa",
        "op": 5,
        "description": "The course focuses on partial differential equations and second-order differential equations.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Partial differential equations (PDE)",
            "Second order ordinary differential equations (ODE)",
            "Special functions"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2013",
        "name": "Fysiikan matemaattiset menetelmät IIb",
        "eng_name": "Mathematical Methods for Physicists IIb",
        "op": 5,
        "description": "The course covers variational calculus, functional derivatives, and operator theory.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Calculus of variations",
            "Functional derivative",
            "Sturm-Liouville equation",
            "Hilbert space",
            "Operators",
            "Spectral theory (if time permits)",
            "Probability calculus (very little)"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "TCM304",
        "name": "Fysiikan matemaattiset menetelmät IIIa",
        "eng_name": "Mathematical Methods for Physicists IIIa",
        "op": None,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["N/A"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Group theory",
            "Representation theory",
            "Topology"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "TCM305",
        "name": "Fysiikan matemaattiset menetelmät IIIb",
        "eng_name": "Mathematical Methods for Physicists IIIb",
        "op": None,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["N/A"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Differentiable manifolds",
            "Riemannian geometry: Geodesics, Killing vectors",
            "Semi-simple Lie algebras and their unitary representations"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1013",
        "name": "Tieteellinen laskenta I",
        "eng_name": "Scientific Computing I",
        "op": 5,
        "description": "The course teaches the basics of programming with Python and the fundamentals of scientific computing.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Programming basics with Python",
            "Structures: for, if, while",
            "Basics of Python language",
            "Jupyter Notebook basics",
            "Linux OS basic commands",
            "Basic concepts of statistical methods (e.g. least squares fit)",
            "Basics of using databases for scientific search",
            "Basics of creating a scientific document (LaTeX/Writing)"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2085",
        "name": "Tieteellinen laskenta II",
        "eng_name": "Scientific Computing II",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Fortran programming language"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1014",
        "name": "Havaintojen tilastollinen käsittely",
        "eng_name": "Statistical Analysis of Observations",
        "op": 5,
        "description": "The course covers statistical processing of observations, error estimation, and distributions.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Basics of statistical processing",
            "Statistical parameters",
            "Basics of probability math and distributions (normal, binomial, poisson)",
            "Statistical estimation and testing (t-test, chi^2, etc.)",
            "Basics of correlation and regression analysis",
            "Basics of time series analysis",
            "Basics of chaos theory"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "MOOC1",
        "name": "Ohjelmoinnin perusteet (MOOC)",
        "eng_name": "Basics of Programming (MOOC)",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Python"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Python",
            "Similar to TiLA1 but more thorough"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "MOOC2",
        "name": "Ohjelmoinnin jatkokurssi (MOOC)",
        "eng_name": "Advanced Programming (MOOC)",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Advanced Python"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Advanced Python",
            "Object-oriented programming",
            "Classes"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "N/A",
        "name": "Introduction to Machine Learning",
        "eng_name": "Introduction to Machine Learning",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "N/A",
        "name": "Advanced Machine Learning",
        "eng_name": "Advanced Machine Learning",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1001",
        "name": "Vuorovaikutukset ja kappaleet",
        "eng_name": "Interactions and Bodies",
        "op": 5,
        "description": "The course gives a good overview of the fundamental forces of nature, conservation laws, and their application.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Matter & Interactions ch 1-8"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Conservation of momentum",
            "Conservation of energy",
            "Forces",
            "4 fundamental interactions",
            "Internal energy",
            "Quantization of energy"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1002",
        "name": "Vuorovaikutukset ja aine",
        "eng_name": "Interactions and Matter",
        "op": 5,
        "description": "The course deepens the understanding of properties of matter and interactions from the perspective of thermodynamics and statistical physics.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Matter & Interactions ch 9-12 + gas supplement"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Translational, rotational and vibrational energy",
            "Collisions",
            "Angular momentum",
            "Entropy",
            "Gases and heat engines"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2027",
        "name": "Mekaniikka",
        "eng_name": "Mechanics",
        "op": 5,
        "description": "The course covers classical mechanics, Lagrangian and Hamiltonian formalisms, and their applications.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": [],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Lagrange mechanics",
            "Hamilton mechanics",
            "Rotation (Euler angles)",
            "Two-body interaction"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1003",
        "name": "Sähkömagnetismi",
        "eng_name": "Electromagnetism",
        "op": 5,
        "description": "The course covers the basics of electric and magnetic fields, circuits, and Maxwell's equations.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Matter & Interactions ch 13-20"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Electric field, force, potential, polarization, charge distributions",
            "Magnetic field, force",
            "Circuits"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS1004",
        "name": "Säteilykentät ja fotonit",
        "eng_name": "Radiation Fields and Photons",
        "op": 5,
        "description": "The student can apply Maxwell's equations to describe time-dependent electrical and magnetic phenomena.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Matter & Interactions ch 21-23"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Maxwell's equations",
            "Electromagnetic radiation"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2016",
        "name": "Elektrodynamiikka I",
        "eng_name": "Electrodynamics I",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Based on Griffiths (start)"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Electrostatics: Electric fields, divergence, curl, potential, work and energy, conductors",
            "Potentials: Laplace equation, method of images, multipole expansion",
            "Electric fields in matter: Polarization, electric displacement, linear dielectrics",
            "Magnetostatics: Lorentz force, Biot-Savart law, Ampère’s law, magnetic vector potential",
            "Magnetic fields in matter: Magnetization, auxiliary field H, linear and non-linear media",
            "Electrodynamics: Electromotive force, induction, Maxwell’s equations"
        ],
        "prereqs": [],
        "prereqs_other": ["Teoreettisen fysiikan taidot (unresolved)"]
    },
    {
        "code": "FYS2017",
        "name": "Elektrodynamiikka II",
        "eng_name": "Electrodynamics II",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["Based on Griffiths (end)"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [
            "Conservation laws: continuity equation, Poynting’s theorem, Maxwell’s stress tensor",
            "Electromagnetic waves: EM waves in vacuum, EM waves in matter, dispersion and absorption, guided waves",
            "Potentials and fields: potential formulation, retarded potentials, Jefimenko, Liénard-Wiechert, moving charges",
            "Radiation: Electric and magnetic dipole radiation, arbitrary sources, radiation reaction",
            "Electrodynamics and relativity: Special relativity, field tensor, Lorentz transformation"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2001",
        "name": "Termofysiikan perusteet",
        "eng_name": "Basics of Thermophysics",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "FYS2002",
        "name": "Termodynaamiset potentiaalit",
        "eng_name": "Thermodynamic Potentials",
        "op": 5,
        "description": "Course description not available in the curriculum.",
        "period": [None],
        "year": [None],
        "content_lectures": None,
        "content_exercises": None,
        "content_other": ["TODO"],
        "themes_theory": None,
        "themes_methods": None,
        "themes_observations": None,
        "themes_phenomena": None,
        "teachers": [],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP338",
        "name": "Gaseous radiation detectors and scintillators",
        "eng_name": "Gaseous radiation detectors and scintillators",
        "op": 5,
        "description": "Knowledge of radiation detectors and its principle of operation, treatment of the signals, and analysis of its performance.",
        "period": [1, 2],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Examination"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Francisco Garcia Fuentes"],
        "topics": [
            "Interaction of radiation with matter",
            "Scintillation mechanism",
            "Gas-filled detectors",
            "Detectors for CERN experiments"
        ],
        "prereqs": [],
        "prereqs_other": ["Applicable already in the beginning of the Master's degree studies"]
    },
    {
        "code": "PAP339",
        "name": "Semiconductor radiation detectors",
        "eng_name": "Semiconductor radiation detectors",
        "op": 5,
        "description": "The student will know the basics of radiation interaction, application of detectors, operational principles of semiconductor detectors, and signal processing.",
        "period": [3, 4],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Participation in two laboratory works", "Final examination"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Jens Brücken"],
        "topics": [
            "Interaction of radiation with matter",
            "Solid-state detectors",
            "Detector read-out"
        ],
        "prereqs": [],
        "prereqs_other": ["Applicable already in the beginning of the Master's degree studies"]
    },
    {
        "code": "PAP340",
        "name": "Physics of semiconductor devices",
        "eng_name": "Physics of semiconductor devices",
        "op": 5,
        "description": "Understand the significance and physical grounds of semiconductor devices, including pn-diodes, light-to-electricity conversion, and transistors.",
        "period": [3, 4],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Participation in laboratory work", "Final examination"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Filip Tuomisto"],
        "topics": [
            "Physics behind the operation of semiconductor devices",
            "Operational principles of various semiconductor devices"
        ],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP328",
        "name": "Laboratory course on instrumentation",
        "eng_name": "Laboratory course on instrumentation",
        "op": 5,
        "description": "After the course the student will be able to work in a scientific laboratory environment, know the physics of radiation detectors, and construct a gas-filled radiation detector.",
        "period": [1, 2],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Participation in laboratory work sessions", "Operational radiation detector", "Accepted work report"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Jens Brücken"],
        "topics": [
            "Laboratory environment",
            "Radiation detector technologies",
            "Gas detectors",
            "Detector read-out systems"
        ],
        "prereqs": [],
        "prereqs_other": ["Basic undergraduate laboratory experience"]
    },
    {
        "code": "PAP327",
        "name": "Particle Physics Phenomenology",
        "eng_name": "Particle Physics Phenomenology",
        "op": 5,
        "description": "Learn to know relativistic kinematics and the Standard model, apply kinematics to cross-section calculations, and understand the Standard model basis and phenomenology.",
        "period": [3, 4],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Exercises", "Oral presentation", "Final oral exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Kenneth Österberg"],
        "topics": [
            "Relativistic kinematics",
            "Standard Model",
            "Beyond the Standard Model",
            "Hadron colliders",
            "LHC phenomenology"
        ],
        "prereqs": ["PAP332", "PAP325"],
        "prereqs_other": ["TCM311 Quantum Field Theory I"]
    },
    {
        "code": "PAP329",
        "name": "Particle Physics Experiments",
        "eng_name": "Particle Physics Experiments",
        "op": 5,
        "description": "Understand the dynamics of particles in an accelerator, learn basic principles of particle detectors, and be able to design a particle accelerator or high energy physics experiment.",
        "period": [3, 4],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Exercises", "Oral presentation", "Final oral exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Kenneth Österberg"],
        "topics": [
            "Accelerators",
            "Beam Dynamics",
            "LHC",
            "Particle Detector History",
            "Tracking and Particle Interaction",
            "Calorimeters",
            "Trigger and Data Acquisition"
        ],
        "prereqs": ["FYS2016"],
        "prereqs_other": ["FYS2005 Kvanttifysiikan sovelluksia I"]
    },
    {
        "code": "PAP331",
        "name": "Computing Methods in High Energy Physics",
        "eng_name": "Computing Methods in High Energy Physics",
        "op": 5,
        "description": "You will learn tools used in the data/physics analysis in a typical High Energy Physics experiment, using the CMS experiment as an example.",
        "period": [3, 4],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Exercises", "Final project", "Home exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Sami Lehti"],
        "topics": [
            "UNIX",
            "C++",
            "ROOT",
            "Event generators",
            "Detector simulations",
            "Reconstruction"
        ],
        "prereqs": [],
        "prereqs_other": ["Programming skills", "Familiarity with Linux", "Introduction to particle physics"]
    },
    {
        "code": "PAP334",
        "name": "Statistical Methods",
        "eng_name": "Statistical Methods",
        "op": 5,
        "description": "Learn the basics of statistics and distributions, hypothesis testing, parameter estimation, and be familiar with confidence intervals and unfolding.",
        "period": [1, 2],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Weekly exercises", "Final home exam", "Final written exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Kenneth Österberg"],
        "topics": [
            "Fundamental concepts",
            "Monte Carlo methods",
            "Hypothesis testing",
            "Parameter & error estimation",
            "Confidence intervals & Unfolding"
        ],
        "prereqs": [],
        "prereqs_other": ["Able to use some statistical library or tool"]
    },
    {
        "code": "PAP325",
        "name": "Introduction to Particle Physics II",
        "eng_name": "Introduction to Particle Physics II",
        "op": 5,
        "description": "The course covers the structure of the Standard Model, quantum chromodynamics, electroweak interactions, neutrino-oscillations, and the Higgs mechanism.",
        "period": [2],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Written final exam", "Homework"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Matti Heikinheimo"],
        "topics": [
            "Quantum chromodynamics",
            "V-A-structure of weak interactions",
            "Neutrino oscillations",
            "Weak interactions of quarks",
            "W and Z bosons",
            "Higgs Mechanism"
        ],
        "prereqs": ["PAP332"],
        "prereqs_other": []
    },
    {
        "code": "PAP332",
        "name": "Introduction to Particle Physics I",
        "eng_name": "Introduction to Particle Physics I",
        "op": 5,
        "description": "Aim is to familiarize students to the basic concepts of modern particle physics and learn the most fundamental calculational techniques.",
        "period": [],
        "year": [3],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Theory exercises", "Experimental analysis", "Oral final exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Mikko Voutilainen"],
        "topics": [
            "Underlying concepts",
            "Decay rates and cross sections",
            "Dirac equation",
            "Interaction by particle exchange",
            "Electron-positron annihilation",
            "Electron-proton elastic scattering"
        ],
        "prereqs": [],
        "prereqs_other": ["Special relativity", "Classical quantum mechanics", "Introduction modern physics", "Structure of matter", "Python"]
    },
    {
        "code": "PAP344",
        "name": "Introduction to the Physics of Neutrinos",
        "eng_name": "Introduction to the Physics of Neutrinos",
        "op": 5,
        "description": "Neutrinos in the Standard Model, neutrino mass terms, mixing, oscillations in vacuum and matter.",
        "period": [],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Homework", "Final exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Anca Tureanu"],
        "topics": [
            "Neutrinos in the Standard Model",
            "Neutrino mass terms",
            "Neutrino mixing",
            "Oscillations of neutrinos in vacuum",
            "Neutrinos in matter"
        ],
        "prereqs": ["PAP325"],
        "prereqs_other": ["Quantum Field Theory I"]
    },
    {
        "code": "PAP346",
        "name": "Path Integral Quantization of Gauge Field Theories",
        "eng_name": "Path Integral Quantization of Gauge Field Theories",
        "op": 5,
        "description": "Brief introduction to path integral, quantization of systems with constraints, path integrals in QFT, and quantization of gauge field theories.",
        "period": [],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Homework", "Final exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Anca Tureanu"],
        "topics": [
            "Path integrals in quantum mechanics",
            "Quantization of systems with constraints",
            "Path integrals in quantum field theory",
            "Grassmann variables",
            "Path integral quantization in QED",
            "Path integral quantization of non-Abelian gauge field theories",
            "Symmetries in functional formalism"
        ],
        "prereqs": [],
        "prereqs_other": ["Quantum Field Theory I and II", "Quantum Field Theory III (recommended)", "Quantum Field Theory IV (recommended)"]
    },
    {
        "code": "PAP347",
        "name": "Theories beyond the standard model",
        "eng_name": "Theories beyond the standard model",
        "op": 5,
        "description": "Course covers theories beyond the Standard Model.",
        "period": [],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": [],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Oleg Lebedev"],
        "topics": [],
        "prereqs": [],
        "prereqs_other": []
    },
    {
        "code": "PAP326",
        "name": "Cosmology II",
        "eng_name": "Cosmology II",
        "op": 5,
        "description": "You will learn to calculate primordial perturbations from inflation, understand structure formation, and how perturbations affect the CMB anisotropy.",
        "period": [2],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Homework problems", "Course exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Hannu Kurki-Suonio"],
        "topics": [
            "Cosmological inflation",
            "Inflation models",
            "Structure formation",
            "Newtonian perturbation theory",
            "Cosmic microwave background anisotropy"
        ],
        "prereqs": ["FYS2081", "FYS1010", "FYS1011", "FYS1012", "FYS2010", "FYS2011", "FYS2012"],
        "prereqs_other": []
    },
    {
        "code": "PAP348",
        "name": "General relativity I",
        "eng_name": "General relativity I",
        "op": 5,
        "description": "You will learn the physical and mathematical structure of the theory of general relativity and how to do calculations including the precession of Mercury and light bending.",
        "period": [3],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Weekly exercises", "Exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Syksy Räsänen"],
        "topics": [
            "Symmetries in Newtonian mechanics",
            "Equivalence principle",
            "Covariant derivative and curvature",
            "Einstein equation",
            "Schwarzschild solution"
        ],
        "prereqs": ["FYS1010", "FYS1011", "FYS2011", "FYS2012", "FYS2027", "FYS2016"],
        "prereqs_other": ["Fundamentals of Theory of Relativity", "Mathematical methods"]
    },
    {
        "code": "PAP349",
        "name": "General relativity II",
        "eng_name": "General relativity II",
        "op": 5,
        "description": "You will learn the physical/math structure of GR, calculations with black holes, linear perturbation theory, gravitational waves, and cosmology.",
        "period": [4],
        "year": [],
        "content_lectures": 0,
        "content_exercises": 0,
        "content_other": ["Weekly exercises", "Exam"],
        "themes_theory": 0.0,
        "themes_methods": 0.0,
        "themes_observations": 0.0,
        "themes_phenomena": 0.0,
        "teachers": ["Syksy Räsänen"],
        "topics": [
            "Action formulation of GR",
            "Global structure of Schwarzschild solution",
            "Black holes",
            "Perturbation theory",
            "Gravitational waves",
            "Killing vectors",
            "FLRW spacetime"
        ],
        "prereqs": ["PAP348"],
        "prereqs_other": []
    }
]
